### ISSUE TITLE
ob-python required for emacs-jupyter

### ISSUE THREAD

**Issue by abradd** [dzop/emacs-jupyter#101]
If ob-python is not loaded by including (python . t) in `org-babel-load-languages` a jupyter-python source block will fail to evaluate with:`org-babel-variable-assignments:jupyter: Symbol’s function definition is void: org-babel-variable-assignments:python` because ob-python functions have not been loaded.

I'm not sure if the same holds for other languages.

I noticed that the README includes an example with (python . t) in `org-babel-load-languages`, but I can't see any explicit statements about its necessity. Or maybe I am missing something? 

What happened in my case was: I came from ob-ipython and replaced the (ipython . t) with (jupyter . t) and left out (python . t) because ob-ipython didn't require it, `org-babel-variable-assignments:python` must have already been loaded because everything was working fine until I restarted emacs.

**Comment by dzop** [comment]
Yes it actually is expected that `(python . t)` is included before `(jupyter . t)` since `ob-python` adds to the `org-babel-tangle-lang-exts` and `org-src-lang-modes` variables that are examined when defining the `jupyter-python` source block in `org-babel-jupyter-aliases-from-kernelspecs`. I guess the README should explicitly mention that `(LANG . t)` is before `(jupyter . t)` since `ob-jupyter` depends on variables extended when loading `ob-LANG`.

The error that you got is actually because we use `org-babel-variable-assignments:python` as the default variable assignment function if one isn't available, so I guess we should actually load this function before attempting to use it.

**Comment by abradd** [comment]
I think a note in the README sounds reasonable.

Loading `ob-python` resolves the  `org-babel-variable-assignments:python` function not being defined so perhaps the note in the README is sufficient for that as well.
