### ISSUE TITLE
Org export with :async yes

### ISSUE THREAD

**Issue by r-zip** [dzop/emacs-jupyter#104]
If I create some source blocks and use org to export LaTeX, the exported document contains the intermediate output of the execution, e.g.

```
2f7955ac-80eb-4e28-8b1c-8d8174c9cb5c
```

Is it possible to export results without disabling async?

**Comment by dzop** [comment]
This is fixed in c0d13396bb356b1ad2582a1c61e9eb6630cace85, but if you are using the MELPA version you don't have that commit due to #77. If you use `use-package` you can install [quelpa](https://github.com/quelpa/quelpa#installation) and modify your `use-package` statement using the method in https://github.com/dzop/emacs-jupyter/issues/61#issuecomment-476764761 until #77 is resolved.

**Comment by r-zip** [comment]
Thanks for the tip. Just installed from quelpa, and it works.
