### ISSUE TITLE
Setting up eldoc integration

### ISSUE THREAD

**Issue by dangom** [dzop/emacs-jupyter#11]
Inspired by the scimax project, I've been trying to setup eldoc support for jupy code blocks.

The following code kind of works, but when `jupyter-inspect` is called from eldoc, the variable `jupyter-current-client` appears to be nil. 

If I `edebug-defun` `jupyter-inspect` and manually set `jupyter-current-client` to `#<jupyter-org-client jupyter-org-client>` (it's the value it has when calling `M-i`), then eldoc will work fine. 

```elisp
(defun scimax-jupyter-eldoc-advice (orig-func &rest args)
  "Advice function to get eldoc signatures in blocks in org-mode."
  (or (scimax-jupyter-signature) (apply orig-func args)))

(defun scimax-jupyter-signature ()
  "Try to return a function signature for the thing at point."
  (when (and (eql major-mode 'org-mode)
	     (string= (or (get-text-property (point) 'lang) "") "jupy-python"))
    (save-window-excursion
     ;;; Essentially copied from (jupyter-inspect-at-point).
      (cl-destructuring-bind (code pos)
      (jupyter-code-context 'inspect)
    (jupyter-inspect code pos nil 0)) ;; Error: will not find jupyter-current-client
      (when (get-buffer "*Help*")
	(with-current-buffer "*Help*"
	  (goto-char (point-min))
	  (prog1
	      (cond
	       ((re-search-forward "Signature:" nil t 1)
		(buffer-substring (line-beginning-position) (line-end-position)))
	       ((re-search-forward "Docstring:" nil t 1)
		(forward-line)
		(buffer-substring (line-beginning-position) (line-end-position)))
	       (t
		nil))
	    ;; get rid of this so we don't accidently show old results later
	    (with-current-buffer "*Help*"
	      (toggle-read-only)
	      (erase-buffer))))))))

(defun scimax-jupyter-turn-on-eldoc ()
  "Turn on eldoc signatures."
  (interactive)
  (advice-add 'org-eldoc-documentation-function :around #'scimax-jupyter-eldoc-advice))
```
I was wondering why it's the case that M-i works as expected and eldoc doesn't. Who is setting jupyter-current-client for `M-i`?!

**Comment by dangom** [comment]
Ok, I found the solution. The trick is to use the macro `jupyter-org-with-src-block-client`.
That's an important distinction of why `jupyter-define-key` should be used instead of simply define-key for the jupyter-org-interaction-mode-map.

**Comment by dangom** [comment]
I think so. I'd be happy to contribute with a PR once I understand better what `jupyter-org-with-src-block-client` is doing and why it is necessary. 

In any case, again, thanks a lot for your project and for your reply.

**Comment by timlod** [comment]
@dangom 
Did you ever finish this code?

I would like to get eldoc integration, and am getting close, but find that there are some issues I still need to fix, specifically multi-line call support.

Namely, if the function call is multi-line, like:
```python
pd.read_csv(
    "file.txt",
    other_arg="something",
)
```
then
```elisp
(cl-destructuring-bind (code pos)
      (jupyter-code-context 'inspect)
    (jupyter-inspect code pos nil 0))
```
doesn't work if the point is not on the line containing the actual function call (ie. line 2 or 3).
This is because by default this call uses `(jupyter-line-context)` - to get it working, a region would need to be set, which gets a bit trickier.

**Comment by nnicandro** [comment]
Would the code context for completions work in this case? If you examine the definition of `jupyter-code-context` for the `completion` type, you'll see that it takes into account nested parenthesis so that in your example if `point` was on the `"file.txt"` line

```python
pd.read_csv(
    "fi|le.txt",
    other_arg="something",
)
```

The code context would be

```python
pd.read_csv(
    "fi
```

I think it would actually make sense to incorporate this in the default code context for the `inspect` type.

**Comment by timlod** [comment]
Trying this out, `jupyter-code-context 'completion` depends on how it's being called - when inside an org src block, the returned `code` is actually the entire src block. Only within the REPL this would return what you posted.
I think for my purposes this is fine, though somewhat unnecessary (that it copies the entire src block).

An ad-hoc solution for Python specifically could call `jupyter-region-context` with `python-nav-beginning/end-of-statement`.

**Comment by nnicandro** [comment]
We can come up with a new type of context, e.g. something like `jupyter-parenthetical-context` which uses `syntax-ppss` similar to how it is used in `jupyter-code-context 'completion` of `jupyter-client.el`. Then we use that as the `jupyter-code-context 'inspect` for `jupyter-org-client.el` and I guess also for the base `jupyter-client.el` version since I think it useful in general for inspections. In fact, maybe we just get rid of the `jupyter-org-client.el` version as it will be the same as the base `jupyter-client.el` version.

I think we can just use what is in `jupyter-code-context 'completion` of `jupyter-client.el` as is, but with the end of the region being `line-end-position` instead of `point` since, for inspections, we want to make sure we capture the whole symbol under `point`.

Your ad-hoc solution raises a point. Would there need to be language specific implementations of code context to make sure we are capturing a syntactically correct region? I don't really think so. I think it is enough that we give some approximate region that includes enough context so that the kernel's parser can figure out the appropriate symbol to inspect. WDYT?

**Comment by timlod** [comment]
That sounds good to me. I will implement this on my end just to get the eldoc integration (for python) working. I could later make a pull request for part of this work, although since they are few changes and you already thought up a good way, you may just want to implement it. How do you feel about including language-specific integrations in this package?   Function signatures and what the inspection returns will differ from language to language, so I think a one-size-fits-all solution (ie. eldoc) probably doesn't exist here.

About your last point, I'm not sure. I'm not experienced in abstract syntax, nor what Jupyter does internally with the provided context. But what you're saying sounds plausible :)
