### ISSUE TITLE
Does emacs-jupyter support  c++?

### ISSUE THREAD

**Issue by hwiorn** [dzop/emacs-jupyter#117]
I want to test the c++ code prototyping using cling(jupyter c++ kernel).

How can i use cling(c++ kernel) with emacs-jupyter?

**Comment by dzop** [comment]
I've only tested the cling kernel briefly with the REPL and it does work, although the C++17 kernel would crash sometimes when typing simple things like `#include <iostream>`, but maybe that is fixed as this was about a month ago. In order to use the cling kernel you just have to make sure that it has a kernelspec in the output of the shell command `jupyter kernelspec list`, then in Emacs, you should be able to start a REPL by typing `M-x jupyter-run-repl` and selecting one of the cling kernels.

Since I don't use C++, there may be other issues. I am willing to help anyone who would like to get the C++ support in better shape if it needs it.

**Comment by dzop** [comment]
Closing this since the short answer is, yes, `emacs-jupyter` supports the cling c++ kernel, more generally, any language that implements the Jupyter messaging spec.
