### ISSUE TITLE
`locate-python` and remote usage

### ISSUE THREAD

**Issue by Giels** [dzop/emacs-jupyter#125]
This is with regard to the python executable used to do the `jupyter_client` ops and such, not about the jupyter kernel's python executable.

Currently, `current-directory` is used as the basis to search for the python executable to use. When trying to connect to a remote kernel (with TRAMP syntax for `:session`), `current-directory` might not point to a remote location but the user might still want the remote location to be probed for the correct python path (often the paths coincide between local and remote so this isn't a problem usually). Additionally, there doesn't seem to be a way to specify which python executable to use (e.g. `jupyter_client` might be installed for python2 on the remote, but the default could be python3, not to mention that jupyter looks for python3 before it looks for python, which I believe should be the opposite...; `locate-python` might then find python3 (currently, due to the settings on the client), but the user might want to use python2 instead).

Maybe a customizable variable and/or an org header-arg should be added to let the user help specify the details of the python to use? Maybe `python-shell-interpreter` can be used? (Though that would still limit the selection to be file-wise at best).

**Comment by dzop** [comment]
> When trying to connect to a remote kernel (with TRAMP syntax for :session), current-directory might not point to a remote location but the user might still want the remote location to be probed for the correct python path 

The `default-directory` is forced to be the `remote` directory specified in the `:session` header argument so it doesn't matter if the `default-directory` of the `org` file is remote or not, see https://github.com/dzop/emacs-jupyter/blob/f491936928b0343a01b727134fb109917da749b3/ob-jupyter.el#L204-L207 

> locate-python might then find python3 (currently, due to the settings on the client), but the user might want to use python2 instead)

There is a possibility that two different pythons can be used when launching a kernel with `default-directory` a remote directory. The python implicitly used by the `jupyter` shell command on the remote and the python found by `jupyer-locate-python`, which prioritizes `python3`.

Are you trying to start a `python2` kernel? If you are, this difference shouldn't matter as long as you are able to install the `jupyter_client` module for both Python versions. The Python returned by `jupyter-locate-python` is only used to launch a kernel using its kernelspec and you can install a `python2` kernelspec even if Jupyter is installed for Python 3, see https://ipython.readthedocs.io/en/stable/install/kernel_install.html#kernels-for-python-2-and-3.

We can also try to avoid this problem by going back to using the `jupyter kernel` shell command to start a kernel on a remote system directly. The reason why we go through Python instead of the `jupyter` shell command is because of issues on Windows. If there is a way to reliably determine if a remote system is a Windows system then we can go through Python on Windows and the `jupyter kernel` command otherwise. On Windows, the issue of finding a Python 3 when the user wants a Python 2 shouldn't happen since the Python executable is usually installed in a separate directory depending on the version. `jupyter-locate-python` should always find the same Python used by Jupyter on Windows.

**Comment by Giels** [comment]
> The `default-directory` is forced to be the `remote` directory specified in the `:session` header argument so it doesn't matter if the `default-directory` of the `org` file is remote or not, see
> 
> https://github.com/dzop/emacs-jupyter/blob/f491936928b0343a01b727134fb109917da749b3/ob-jupyter.el#L204-L207
Alright. So the executable found on the remote will not be influenced by the local `default-directory` setting.

> There is a possibility that two different pythons can be used when launching a kernel with `default-directory` a remote directory. The python implicitly used by the `jupyter` shell command on the remote and the python found by `jupyer-locate-python`, which prioritizes `python3`.
There are other options. For example, there can be a locally installed python and a globally installed python (which could also both be python3). This is especially common for python installs managed by frameworks like anaconda et al. (this also applies to the jupyter installation on the remote: there may be multiple ones, so that `jupyter --paths` may not return what the user likes). I shouldn't have mentioned python2 vs python3 as an example because I see it confused the issue.

> Are you trying to start a `python2` kernel?
Sorry if that wasn't clear, what I meant by 'not the jupyter kernel's executable' is that I was not concerned with the kernel launched by the remote jupyter, just the `jupyter-locate-python` choice of python.

> We can also try to avoid this problem by going back to using the `jupyter kernel` shell command to start a kernel on a remote system directly. The reason why we go through Python instead of the `jupyter` shell command is because of issues on Windows. If there is a way to reliably determine if a remote system is a Windows system then we can go through Python on Windows and the `jupyter kernel` command otherwise. On Windows, the issue of finding a Python 3 when the user wants a Python 2 shouldn't happen since the Python executable is usually installed in a separate directory depending on the version. `jupyter-locate-python` should always find the same Python used by Jupyter on Windows.
Perhaps the best solution would be to keep the current behavior but to somehow allow users to provide the exact path to the executable to use?

**Comment by dzop** [comment]
> There are other options. For example, there can be a locally installed python and a globally installed python (which could also both be python3). This is especially common for python installs managed by frameworks like anaconda et al.

Oh ok, yes there can be other pythons when considering `conda` and the like, but their executables wouldn't be in the same directory as the `python` that Jupyter uses so I don't see how the path finding logic would find them. `jupyter --paths` always returns a path derived from the `sys.prefix` of the `python` it was installed with. So usually `jupyter-locate-python` will return a path `<sys.prefix>/bin/python3?`.

> (this also applies to the jupyter installation on the remote: there may be multiple ones, so that jupyter --paths may not return what the user likes)

Isn't the `python` used by Jupyter the one the user "likes" since the `jupyter` command uses it?

**Comment by Giels** [comment]
The problem is that the `jupyter` command may be, say, `/usr/bin/jupyter`, whereas the user wants to use `~/conda/bin/jupyter`. Then, the `jupyter --paths` command will return what `/usr/bin/jupyter` thinks the user likes (that is, the behavior should be exactly as you say above). It might not be practical or desirable for the user to change, e.g., their `PATH`, to accommodate for that when using emacs-jupyter.
As far as I'm aware there isn't a way to resolve this on the user-end in that case.

**Comment by dzop** [comment]
I think the standard way to account for these kinds of issues with `PATH` when using TRAMP is to add paths to `tramp-remote-path`. See https://www.gnu.org/software/emacs/manual/html_node/tramp/Remote-programs.html and in particular the part about `tramp-own-remote-path`.

**Comment by Giels** [comment]
Thanks. I think this solves most of this. I still think it would be more useful to be able to set the path to `python` directly for emacs-jupyter, but this addresses my specific use case.
