### ISSUE TITLE
Does async respect :eval never-export and :exports both?

### ISSUE THREAD

**Issue by dangom** [dzop/emacs-jupyter#134]
Trying to export to HTML via `C-c C-e h o`. 
Have following props:

```org
:PROPERTIES:
:header-args:jupyter-python: :session ~/kernels/remote.json :eval never-export :exports both
:END:
```

Blocks seem to read this, because the src-block eldoc hints show the config to be correct. However, the export is missing the images and attempts to evaluate async src blocks, which I think are not the expected behaviour.

**Comment by dzop** [comment]
`emacs-jupyter` doesn't handle the `:eval` and `:export` settings in any way. All that is provided by `emacs-jupyter` is the `org-babel-execute:jupyter` function (which currently only looks at the `:file`, `:results`, and `:async` settings) so the decisions about when to evaluate during export and what to export are all handled by `org-mode`.

Looking at the `org-mode` sources, the `org-babel-check-confirm-evaluate` function is what handles the `:eval` parameter. If that function returns `nil`, then the `org-babel-execute:jupyter` function is never called by `org-babel-execute-src-block`. So maybe `org-babel-check-confirm-evaluate` is not returning what you are expecting given your setup? The only way I can see that happening, based on its definition, is if the `org-babel-exp-reference-buffer` is not set during export somehow. I haven't looked into the specifics about the `:exports` setting.

I just tried `C-c C-e h o` (after evaluating the src block manually and having the current directory being the `emacs-jupyter` source directory which contains the `jupyter.png` file) with the following tree

```org
* Export
:PROPERTIES:
:header-args:jupyter-python: :eval never-export :exports both
:END:

#+begin_src jupyter-python
from IPython.display import Image
Image(filename='jupyter.png')
#+end_src
```

and I got these messages in `*Messages*`

```
org-babel-exp process jupyter-python at position 92...
Evaluation of this jupyter-python code block is disabled.
```

and the resulting HTML file that opened in the browser showed both the source code and the image file. This is on the current `master` version, but you should be seeing the same results if you are on `v0.8.0` or later since there haven't been any changes to exporting since then (I'm pretty sure). Also I'm on Org `v9.2.2`.

**Comment by dangom** [comment]
Ok, I found the issue. I had a heading with a different session and I forgot to add the `:eval never-export` to that heading as well.
