### ISSUE TITLE
Beginning-of-line not working if point passed the last char in the REPL

### ISSUE THREAD

**Issue by dangom** [dzop/emacs-jupyter#14]
Babel switch to session, then paste some code on the REPL. Beginning-of-line doesn't work then unless I move a char back first. Wondering if that's just at my end?

Emacs 26.1, MacOS 10.13, Org 9.2, Python 3.7.1

**Comment by dzop** [comment]
Pasting does look like it isn't working. The text properties that are being added in `jupyter-repl-do-after-change` seem to be removed, e.g. the `field` text property that is added in `jupyter-repl-mark-as-cell-code` is removed after pasting. This property is important for fontification in `jupyter-repl-font-lock-fontify-region` and for the text motion commands to stop at the beginning and end of cell code.

From some initial investigation it looks like this is because `yank-excluded-properties` contains the `field` property which means after pasting (and after `jupyter-repl-mark-as-cell-code` has fired) it removes the property.

In the REPL the `field` property is added to the cell code to distinguish it from cell output and allows motion commands like `beginning-of-line` to stop at the beginning and end of the cell code since they stop their motion at field boundaries. Although if the `field` property is removed from pasted text, `beginning-of-line` should still work so this may just be another bug and not completely related to your issue.

Could you run

```emacs-lisp
(setq-local yank-excluded-properties (remq 'field yank-excluded-properties))
```
in the REPL buffer and then paste again to see if it works.

**Comment by dangom** [comment]
Not really, unfortunately. 
Also killing a line after pasting doesn't seem to work. Toggling debug on error gives (but not sure if problem is related):

```
Debugger entered--Lisp error: (error "Cell for request not found")
  signal(error ("Cell for request not found"))
  error("Cell for request not found")
  (if (catch 'done (while (= (jupyter-repl-previous-cell) 0) (if (eq (jupyter-repl-cell-request) req) (progn (throw 'done t))))) nil (error "Cell for request not found"))
  jupyter-repl-goto-cell(#s(jupyter-request .....
```

I don't know yet how to reproduce, but some combinations of keybindings (including yanking) can also cause the REPL to hang at my end. Will investigate when I have more time.

**Comment by dzop** [comment]
OK, I think this problem still has something to do with the `field` text property.

If you set `inhibit-field-text-motion` to `t` and then paste and try `beginning-of-line`  does it work? I think killing a line should also work if you do this.

**Comment by dangom** [comment]
Yes, that does fix beginning of line. Killing also works, but it raises the message below which I can apparently ignore.

```
Debugger entered--Lisp error: (error "Not in code of cell")
  signal(error ("Not in code of cell"))
  error("Not in code of cell")
  (if (jupyter-repl-cell-line-p) nil (error "Not in code of cell"))
  jupyter-repl-cell-code-position()
  (let* ((pos (jupyter-repl-cell-code-position)) (code (jupyter-repl-cell-code)) (replacement (let ((clientvar jupyter-current-client)) (save-current-buffer (set-buffer jupyter-repl-lang-buffer) (let ((inhibit-read-only t) (jupyter-current-client clientvar)) (erase-buffer) (insert code) (goto-char pos) (let ((tick (buffer-chars-modified-tick))) (jupyter-indent-line) (if (eq tick (buffer-chars-modified-tick)) nil (setq pos (point)) (buffer-string)))))))) (if replacement (progn (jupyter-repl-replace-cell-code replacement) (goto-char (+ pos (jupyter-repl-cell-code-beginning-position))))))
  jupyter-repl-indent-line()
  indent-according-to-mode()
  indent-region-line-by-line(1389 1390)
  indent-region(1389 1390 nil)
  sp--indent-region(1389 1390)
  sp--cleanup-after-kill()
  sp-kill-hybrid-sexp(nil)
  funcall-interactively(sp-kill-hybrid-sexp nil)
  call-interactively(sp-kill-hybrid-sexp nil nil)
  command-execute(sp-kill-hybrid-sexp)

```

**Comment by dzop** [comment]
OK, the issue with `beginning-of-line` not working after yanking is because `insert-for-yank` will put a `rear-nonsticky` property on the last character after the pasted text.

After pasting, `point` is at `point-max` which does not have a `field` property but the last character pasted, the one with the `rear-nonsticky` property and which is part of the cell code, does. From the documentation on [fields](https://www.gnu.org/software/emacs/manual/html_node/elisp/Fields.html), if `point` is at the boundary of two fields (the cell code's field and the nil field) then, because the last character of the cell code's field has the `rear-nonsticky` property, `point` is associated with the nil field.

Why this matters is that the motion commands like `beginning-of-line` will stop at the boundaries of the fields that `point` is associated with. Since `point-max` is associated with the nil field and not the cell code, when you call `beginning-of-line` `point` stays at `point-max`.

I think the simplest solution would be to remove the `rear-nonsticky` property added by `insert-for-yank`.

**Comment by dangom** [comment]
With `(add-hook 'jupyter-repl-mode-hook #'(lambda () (setq-local inhibit-field-text-motion t))`, inspired by your earlier suggestion, I can yank without any problems. Is there a reason why `rear-nosticky` is important? Are there any side-effects of removing it?

(I still notice errors that I can apparently safely ignore using the REPL, though. If I org babel switch to session after running an org block, then doing anything in the REPL and pressing RET will give me a message saying `Error running timer ‘jupyter-handle-message’: (error "Cell for request not found")`. It I switch to the REPL before running org blocks, then the message doesn't appear)

**Comment by dzop** [comment]
OK, I have removed the rear-nonsticky property added by `insert-for-yank`. There shouldn't be any side effects. It is there so that whenever the text that you type after pasting doesn't inherit any of the text properties of the pasted text, but this shouldn't be an issue with the major modes of the kernel languages supported by Jupyter. 

Could you make another issue for the `Cell for request not found` error. I tried to reproduce the issue by running the following code block

```python
#+BEGIN_SRC jupy-python
import time
time.sleep(5)
#+END_SRC
```

then calling `org-babel-switch-to-session`, but couldn't reproduce the problem. In the new issue could you give a minimum number of steps necessary to reproduce the problem.
