### ISSUE TITLE
Channel not started in ioloop subprocess (:iopub)

### ISSUE THREAD

**Issue by Yevgnen** [dzop/emacs-jupyter#148]
Sometimes `emacs-jupyter` can not start a kernel, and there's no error raised but not a message `Channel not started in ioloop subprocess (:iopub)` is displayed. It's quite strange and happened not that often. Usually the first time I start a kernel in a fresh `Emacs` session, then I can start a kernel in that `Emacs` session. And I have to restart `Emacs`.

 With `jupyter--debug` is on, the debug message looks like

```
executing Jupyter-Python code block...
jupyter-start-kernel: default-directory = /Users/user/git/competitions/xunfei2019/
jupyter-start-kernel: Starting process with args "python -m ipykernel_launcher -f /Users/user/Library/Jupyter/runtime/emacs-kernel-JprynY.json"
Starting python3 kernel process...done
MESSAGE: (:iopub :status (:execution_state starting))
RUN-HOOK: jupyter-iopub-message-hook
Channel not started in ioloop subprocess (:iopub)
```

After the error is displayed, I noticed that file `/Users/user/Library/Jupyter/runtime/emacs-kernel-JprynY.json` does not exist.

**Comment by dzop** [comment]
Does increasing `jupyter-default-timeout` to something like `(* 2 jupyter-default-timeout)` help any? For every kernel launched there is also an "ioloop" process that is started which does the actual communication with the kernel. The ioloop process does all of the JSON encoding/decoding and message sending/receiving (the input/output) to the kernel, the parent Emacs process just deals with the plist representations of the messages.

When we start the ioloop process, the parent Emacs process sends the connection information it needs to start the Jupyter channels, e.g. `:iopub`, and waits for confirmation that the subprocess did indeed start those channels. If you get the `Channel not started...` error that means that confirmation wasn't sent within the timeout period we are willing to wait for it (`jupyter-default-timeout`).

What's curious is that you get a message that arrived on the `:iopub` channel before the error
```
MESSAGE: (:iopub :status (:execution_state starting))
```
so that channel was started, it just looks like we just didn't get the confirmation in time. Based on this, I don't think increasing `jupyter-default-timeout` will help. I think it has to do with how we are waiting for confirmation that a channel was started

https://github.com/dzop/emacs-jupyter/blob/7c1689e33d0a21c7bd259e8b0277e62c56af1619/jupyter-channel-ioloop-comm.el#L155-L157

The internals of that `jupyter-ioloop-wait-until` call are essentially equivalent to

```emacs-lisp
(while (not (eq (jupyter-ioloop-last-event ioloop) 'start-channel))
  (sleep-for ...))
``` 

Confirmation that a channel was started corresponds to a `start-channel` event received by the parent Emacs process from the ioloop process. That `status: starting` message you got corresponds to a `message` event the ioloop process sent to the parent Emacs process.

What seems to be happening is that you get an event stream like (`start-channel`, `message`) in one `sleep-for` call which means that the next check of `jupyter-ioloop-last-event` will be `message`. This appears to be the cause of the error. You had received confirmation that the channel was started, but `jupyter-ioloop-wait-until` didn't catch it since another event came in before it got a chance to check for the `start-channel` event.

I see two options here: (1) fix `jupyter-ioloop-wait-until` so that it can handle the case of multiple events coming in while sleeping or (2) remove the `jupyter-ioloop-wait-until` call completely and just use

```emacs-lisp
(jupyter-with-timeout
    (nil jupyter-default-timeout
         (error "Channel not started in ioloop subprocess (%s)" channel))
  (jupyter-channel-alive-p comm channel))
```

**Comment by Yevgnen** [comment]
Thanks for the very details. I test the latest version these two days and it probably fixes the issue.
