### ISSUE TITLE
Convenient way to save figure from the REPL?

### ISSUE THREAD

**Issue by dangom** [dzop/emacs-jupyter#149]
I know this goes against any reproducibility initiatives, but is there a way to quickly get the path of a figure output in the REPL?

**Comment by dzop** [comment]
You should be able to use `M-x image-save` with `point` on the image.

**Comment by dangom** [comment]
Awesome :) That works just fine. Thanks! And do you think it's possible to configure the recent image display fix to also work at the REPL? I've set org-image-actual-width to '(400) but that seems to only work at the org buffer

**Comment by dzop** [comment]
The `org-image-actual-width` changes are pretty specific to `org-mode` (see `jupyter-org-adjust-image-size`) so I don't see how we could bring those changes into the REPL.

The width used for each image in the REPL is already the actual width. Are you saying you would want to be able to scale the images in the REPL?

**Comment by dangom** [comment]
Yes, now that I learned it's so easy to save images from the REPL I tried increasing the dpi, but then images get way too large.

**Comment by dzop** [comment]
I don't see myself working on this feature any time soon, but you should be able to get something going by modifying the `jupyter-insert-image` function

https://github.com/dzop/emacs-jupyter/blob/6b86fedb1010158fe584fa050c51ac088c91882f/jupyter-mime.el#L468

probably by adding a new customizable variable to set the width if it isn't already present. Pull requests welcome :).

**Comment by dangom** [comment]
Hey dzop, thanks again. This is totally low priority. I wondered whether there'd be an easy (perhaps even already built-in) way to control that.
I'll have a look at `jupyter-insert-image` and see if I can come up with something useful.

In any case, thanks as always. Really awesome project

**Comment by dzop** [comment]
There is the `image-scaling-factor` variable which may also work, but this applies to all images. You can probably set this as a local variable in the REPL buffer though so that it only applies to images created in the REPL buffer.

**Comment by Yevgnen** [comment]
I also looking for a way to control the image size in repl, with high dpi I can't see the whole image with emacs's default scrolling...

**Comment by dangom** [comment]
I tried playing with both `image-scaling-factor` and `jupyter-insert-image`, but neither seemed to have an effect on the size of the images.

**Comment by dzop** [comment]
If you replace `type` with `imagemagick` in the `create-image` call of `jupyter-insert-image` does it change anything? I think I'm using the `:width`, `:height`, and `:mask` parameters wrong there. Those are only available for `imagemagick` type images (https://www.gnu.org/software/emacs/manual/html_node/elisp/ImageMagick-Images.html) I think.

**Comment by dangom** [comment]
No, but then I think I must be doing something wrong because I can't seem to get edebug-defun to trigger on `jupyter-insert-image`

**Comment by dzop** [comment]
Yeah that happens for many functions. I think it has to do with the fact that they are run through timers and so are somewhat asynchronous.

I would just capture the arguments for one call of `jupyter-insert-image`, e.g. placing the line

```(setq jupyter-insert-image-args (list data type metadata))```

as the first line in the function body before it gets called. This way you can just call the function like

```(apply #'jupyter-insert-image jupyter-insert-image-args)```

for testing purposes.

Also what happens if you remove the `:height` parameter while keeping just the `:width` and having the `type` be `imagemagick`?

**Comment by dangom** [comment]
Sorry for the long absence.
Removing `:height` and keeping just `:width` or using `:scale` work just fine, provide we change type to 'imagemagick, as you suggested.

```elisp
(defun jupyter-insert-image (data type &optional metadata)
  "Insert image DATA as TYPE in the current buffer.
TYPE has the same meaning as in `create-image'. METADATA is a
plist containing :width and :height keys that will be used as the
width and height of the image."
  (setq jupyter-insert-image-args (list data type metadata))
  (cl-destructuring-bind (&key width height needs_background &allow-other-keys)
      metadata
    (let ((img (create-image
               ;; data type 'data :width width :height height
                data 'imagemagick 'data :scale 0.5
                :mask (when needs_background
                        '(heuristic t)))))
      (insert-image img))))
```

The issue seems to be that `metadata` is nil, so `width` and `height` are also nil, which makes it hard to decide programatically whether images should be downscaled.

**Comment by dzop** [comment]
Its fine if `metadata` doesn't contain any information, but I do think we should consider it if it does. For example, if either `height` or `width` is specified then we add the corresponding property for the `create-image` call. If both are specified, then just use `width` since no one probably wants a stretched image.

If you want to get the width of an image as Emacs sees it you can use the `image-size` function which will cache the rendered image immediately to calculate its size.

So something like below

```emacs-lisp
(let* ((image (create-image data type 'data))
       (image-width (car (image-size image 'pixels))))
  (if (image-type-available-p 'imagemagick)
      (apply #'create-image data 'imagemagick 'data
             (append (when (> image-width 500) (list :scale 0.5))
                     (when needs_background (list :mask '(heuristic t)))))
    image))
```

You probably want to be more clever and include `width` somehow when creating the `imagemagick` image and maybe a max `width` should be used, not necessarily `scale`?

This may be slow because it causes up to two images to be rendered by Emacs. One to calculate the image size and another one for the re-scaled image.
