### ISSUE TITLE
default-header-args ignored in latest version

### ISSUE THREAD

**Issue by benneti** [dzop/emacs-jupyter#151]
Hi, since my last update the header args I set in my configuration are not loaded anymore (without any error).
```
(with-eval-after-load 'ob-jupyter
  ;; Sane default header args for jupyter
  (setq org-babel-default-header-args:jupyter-julia
        '((:async . "yes")
          (:results . "raw drawer")
          (:exports . "both")
          (:session . "jl")
          (:kernel . "julia-1.1"))))
```
It doesn't work without the` with-eval-after-load` either.
Also is there a way one could use `add-to-list` instead of `setq` such that I do not have to set the kernel manually?
(This does not work for me because then it tells me that the variable I want to add to is void)

**Comment by dzop** [comment]
> header args I set in my configuration are not loaded anymore

Whoops. I think this is because of 0f01a2a2ed36ffc676d1d5f39e2c3f562ad2ca03, sorry. I didn't think about this issue before I made the change. I stopped creating the language aliases (which includes the default-header-args variables) when loading `ob-jupyter` because I didn't want to run any shell commands during load time which I don't think is correct since a user's `exec-path` may not be setup correctly at load time.

> It doesn't work without the `with-eval-after-load` either.

This is because we overwrite the variable when making the language aliases. We probably shouldn't do this and use the variable if it is already defined.

> such that I do not have to set the kernel manually?

Maybe we can add the `:kernel` if it is missing from the variable when making the language aliases.

**Comment by benneti** [comment]
Adding the kernel sounds like a good idea

**Comment by dangom** [comment]
I have the following in my config (simplified) to work around this

```elisp
;; This initial `use-package' loads ob after org with jupyter-independent settings.
(use-package ob
  :after org
  :demand t
  :straight nil
  :config
  (dolist (language '((org . t)
                      (python . t)
                      (shell . t)
                      (latex . t)))
    (add-to-list 'org-babel-load-languages language))
  (org-babel-do-load-languages 'org-babel-load-languages org-babel-load-languages))

(use-package jupyter
  :demand t
  :after org
  :config
  (add-to-list 'org-babel-load-languages '(jupyter . t))
  (org-babel-do-load-languages 'org-babel-load-languages org-babel-load-languages))

;; This second `use-package' declaration only demanded after both jupyter and python
;; have been loaded. This guarantees that the org-babel-default-header-args for python
;; will exist.
(use-package ob
  :demand t
  :straight nil
  :after (:all jupyter python)
  :config
  ;; Set better default settings for org-babel.
  (setf (alist-get :async org-babel-default-header-args:jupyter-python) "yes")
  (setf (alist-get :session org-babel-default-header-args:jupyter-python) "py3"))
```

**Comment by dzop** [comment]
OK, I've just reverted back to the old behavior of potentially calling shell commands at load time. @dangom just reminded me that the usual way of loading `ob-jupyter` is through `org-babel-do-load-languages` so its kind of expected that all the language aliases already be defined after calling that function.

**Comment by Yevgnen** [comment]
This reversion seems has effect that if `ob-jupyter` failed to setup for `org-mode`, then it won't fix automatically. For example,

```
Error retrieving kernelspecs: (error "Can’t obtain kernelspecs from jupyter shell command")
```

This error can happen when one only use `jupyter` in `virtualenv` as no `jupyter` executable outside this env and does not want to use any babel block in an `org` session. The next time he wants to use `jupyter` in another `org` buffer with switching to the proper `vritualenv`, he will fail

```
No org-babel-execute function for jupyter-python!
```

**Comment by dzop** [comment]
You can evaluate `(org-babel-jupyter-aliases-from-kernelspecs 'refresh)` when you switch virtual environments to one containing a `jupyter` executable.

**Comment by Yevgnen** [comment]
It still failed to set up `jupyter-org-interaction-mode`, key bindings like `C-c h` don't work.

**Comment by dzop** [comment]
So `org-mode-hook` doesn't have `jupyter-org-interaction-mode` in it? That is odd since the file that adds it to the hook (`jupyter-org-client`) 

https://github.com/dzop/emacs-jupyter/blob/6b86fedb1010158fe584fa050c51ac088c91882f/jupyter-org-client.el#L663

and the file that adds the `C-c h` binding (`jupyter-org-extensions`)

https://github.com/dzop/emacs-jupyter/blob/6b86fedb1010158fe584fa050c51ac088c91882f/jupyter-org-extensions.el#L670

are `require`d at the top of `ob-jupyter` 

https://github.com/dzop/emacs-jupyter/blob/6b86fedb1010158fe584fa050c51ac088c91882f/ob-jupyter.el#L36-L37

so by the time you get the `Error retrieving kernelspecs` error (which occurs at the bottom of the file) `jupyter-org-interaction-mode`  should be in `org-mode-hook` and the `C-c h` bindings should be in its keymap.

Are there any other errors that you may have missed besides `Error retrieving kernelspecs`?

**Comment by Yevgnen** [comment]
It's in `org-mode-hook`. I found that I should `revert-buffer` again to let it take effect.

**Comment by dzop** [comment]
Closing since the original issue has already been addressed.
