### ISSUE TITLE
Kernel not alive error during remote session

### ISSUE THREAD

**Issue by hilman-dayo** [dzop/emacs-jupyter#164]
Hello. Thanks for the awesome package.

I have one problem with this package.
While connecting to a Python kernel through SSH (using `:session`), I will access the session's REPL through `org-babel-switch-to-session`.
However, at the REPL, sometimes it will say `Kernel not alive`, making me not being able to do anything through the REPL. But, if I evaluate something through org-babel code block (in the same session), it is perfectly fine.

For example, let say I have a kernel running with a session named `/ssh:DL:/run/user/1000/jupyter/kernel-6a17b9bb-df04-4100-b71f-d94832ecadb9.json`.
If I open the REPL with  `org-babel-switch-to-session` and typed `print("hai")`, I will get `Kernel not alive` message. But, if I write the same thing in a `jupyter-python` code block and evaluate it using the same session, I have no problem at all.

**Comment by dangom** [comment]
@hilman-dayo  issue seems like a dupe of #141

**Comment by dzop** [comment]
OK, I've increased the timeouts so this problem shouldn't happen unless you have an extremely slow connection. I think the timeouts were too low in the first place.

I've made it so that a total of 30s has to elapse before considering that the kernel isn't alive, more specifically is we don't receive a ping from the kernel after three consecutive 10s periods the kernel is considered dead. Before it was five 1s periods.

Please close the relevant issues if you no longer experience problems after updating.

**Comment by hilman-dayo** [comment]
I had this problem when I was in UK and my machine is in Japan. Since I already come back to Japan, I can't test and try to reproduce this problem (at least, for this time being).
However, since theoretically, this problem should already be solved by the latest commit, I will close this issue. I will surely get back to it if it occurred back.

**Comment by NightMachinary** [comment]
Will a timeout also kill the kernel process? Every few hours my kernels become "not alive," and their processes are also dead.
