### ISSUE TITLE
Relative path to kernel json on TRAMP

### ISSUE THREAD

**Issue by jackkamm** [dzop/emacs-jupyter#185]
If I start a kernel in the same directory as my org file like so:
```
jupyter console -f ./test.json --kernel julia-1.2
```

Then connect to the kernel through a relative path in the `:session` header like so:
```
#+begin_src jupyter-julia :session ./test.json
  x = 1+1
#+end_src
```

Then it works if the org file is on my local machine, but not if the org file is accessed remotely through TRAMP.

**Comment by dzop** [comment]
That's probably because we just pass the session as is to `jupyter-connect-repl`

https://github.com/dzop/emacs-jupyter/blob/dcf80d51dbf9c8eea9679d5a54ca771221d6a1e0/ob-jupyter.el#L305

To get it working I think all that is needed is to replace `session` with `(expand-file-name session)`. The value of `session` will eventually be passed to `jupyter--connection-info` which only tunnels a connection if a file name passed to it is a remote file name.

https://github.com/dzop/emacs-jupyter/blob/dcf80d51dbf9c8eea9679d5a54ca771221d6a1e0/jupyter-client.el#L303-L309

Probably not the best place to put the tunneling logic...

If you get it working with the above change either submit a pull request or let me know here. Thanks.

**Comment by jackkamm** [comment]
Thanks for the pointers -- I'll look into it some time in the next couple days and report back.

The one point I am currently unsure about is whether replacing `session` with `(expand-file-name session)` will mess up using `/run/user/1000/jupyter` as the default directory to look for kernels.

**Comment by dzop** [comment]
Should be fine, after connecting to a kernel using `jupyter-connect-repl` a `:kernel-info-request` is sent to the kernel and the response is used to figure out the language of the kernel.

Looking for kernels only matters when Emacs is the one that is starting the kernel process.

**Comment by jackkamm** [comment]
Sorry I misspoke -- when I said "kernel", I meant "session". That is, I was concerned that using `(expand-file-name session)` will mess up the behavior of looking for the session JSON file in the default folder `/run/user/1000/jupyter` if the path isn't specified. I'll be sure to test this behavior when I try this out.

**Comment by jackkamm** [comment]
I think I was confused, for some reason I thought that if only the basename of the JSON was specified it would look in the default location (e.g. `/run/user/1000/jupyter`) but on testing again it seems I was wrong. So the fix really is as simple as you say, PR incoming.
