### ISSUE TITLE
can't run jupyter-run-repl

### ISSUE THREAD

**Issue by prittjam** [dzop/emacs-jupyter#23]
When I run `M-x jupyter-run-repl`, it can't find any kernels. It just says `No kernel found for prefix (nil)`

**Comment by dzop** [comment]
Can you evaluate

```
(shell-command "jupyter kernelspec list")
```

and show the output that it produces. The above shell command is how `emacs-jupyter` gets access to the kernelspecs.

**Comment by prittjam** [comment]
Available kernels:
  python3    /home/jbpritts/.local/share/jupyter/kernels/python3
  python2    /usr/share/jupyter/kernels/python2

I'm using a virtual environment, and I use the first kernel for that.

**Comment by dzop** [comment]
OK could you evaluate the following

```
(mapcar (lambda (k) (plist-get (cddr k) :display_name))
   (jupyter-available-kernelspecs))
```

and show its value.

**Comment by prittjam** [comment]
("Python 3" "Python 2")

**Comment by dzop** [comment]
OK, that's weird because that last snippet is basically what is used to find the kernelspecs in `jupyter-run-repl` and if it is returning a non-nil value then `jupyter-run-repl` should work. Are you doing `M-x jupyter-run-repl` or calling `jupyter-run-repl` manually, in the first former case it should be working.

Are you able to get a non-nil return value when you evaluate

```
(jupyter-completing-read-kernelspec)
```

**Comment by prittjam** [comment]
I run `M-x jupyter-run-repl`

When I evaluate (jupyter-completing-read-kernelspec) it prompts with kernel:

If I enter Python 3 I get 
("python3" "/home/jbpritts/.local/share/jupyter/kernels/python3" :argv ["/home/jbpritts/venv/py36/bin/python" "-m" "ipykernel_launcher" "-f" "{connection_file}"] :display_name "Python 3" :language "python")

Now if I run jupyter-run-repl and enter Python 3 when it prompts for kernel: I get
(wrong-type-argument stringp nil)
make-temp-file: Creating file with prefix: No such file or directory, /run/user/1001/jupyter

**Comment by dzop** [comment]
OK that `make-temp-file` error is a known problem that should have been fixed by the latest master. So if you pull in the latest changes that error should go away.

But is the original `No kernel found for prefix (nil)` error still happening?

**Comment by prittjam** [comment]
Well when it prompted for kernel:, I wasn't sure what to put there. Since I saw  `("Python 3" "Python 2")` I entered `Python 3` and that is the string that causes the `make-temp-file` problem. However, I just cloned your repository yesterday, so it should include the bug fix.

**Comment by prittjam** [comment]
OK, I see that you just committed the fix 3 hours ago. I will try it.

**Comment by prittjam** [comment]
Ok, it gets further, but now fails with, `Kernel did not read connection file within timeout`

**Comment by dzop** [comment]
OK that error is happening because we start up the kernel process and wait for it to read the connection file that was written to the runtime directory (the `/run/user/1001/jupyter` directory in your case) before proceeding with the rest of the REPL initialization for synchronization purposes.

If your using a custom python kernel maybe it takes a long time to read the connection file? You can try
evaluating

```
(setq jupyter-long-timeout 20)
```

and then call `jupyter-run-repl`. The default value of the timeout is 10 seconds.

Also, as a sanity check, make sure you can run Jupyter normally through the command line, i.e. does `jupyter console --kernel=python3` work as expected?

**Comment by prittjam** [comment]
It works now; it was a problem with the virtual environment. I created a kernel for the virtual environment with 
`python -m ipykernel install --user --name ENVNAME --display-name "Python (whatever you want to call it)"`

**Comment by dzop** [comment]
Glad it is working! If you have any ideas on how the documentation could be improved so that users who have similar issues are better informed, feel free to open a pull request.
