### ISSUE TITLE
Send region of code to jupyter-repl with C-c C-c

### ISSUE THREAD

**Issue by prittjam** [dzop/emacs-jupyter#26]
I use elpy to edit .py files and want to send a region of code to a running jupyter-repl for evaluation. Also it would be nice to launch a REPL if it is not running and `C-c C-c` is invoked. I suspect the needed command is something like 

`(setq python-shell-interpreter "jupyter-repl")`

**Comment by dzop** [comment]
You can associate the current buffer with a REPL by calling `M-x jupyter-repl-associate-buffer`.

**Comment by prittjam** [comment]
I tried this mode. I can execute code regions with C-c C-c, but it works a little differently than other REPL interfaces I've tried. Typically the code is copied into a cell in jupyter and executed. With emacs-jupyter, It seems that the code is executed but not copied to a cell in the jupyter REPL. So the state is there, but no record of the code in the REPL. This may just be a matter of preference.

**Comment by prittjam** [comment]
If I call `M-x jupyter-repl-associate-buffer`, then I cannot attach to a jupyter session being used by org-mode. It says `No REPL for major-mode exists`. Should this be possible? This is after I call `M-x org-babel-switch-to-session`

**Comment by dzop** [comment]
It does make sense to be able to associate the session of a Jupyter src-block with a source code buffers since it does have an underlying REPL. This does seem to be a bug which should be fixed on the latest master.  

It is debatable that we should also store the history of code evaluated using `C-c C-c`. This is definitely workflow dependent since I like to repeatedly evaluate code using `C-c C-c`, that I don't necessarily want to see in my REPL history and definitely don't want cluttering the REPL. I prefer the REPL history to contain what I actually typed at the REPL itself.

The traceback issue also seems workflow dependent since I don't usually have the REPL window displayed when evaluating code using `C-c C-c` and having the traceback pop up is useful.

Also for reference, the way REPLs in Emacs (those which use `comint-mode` like `elpy`) communicate with their REPL process is very different from how `emacs-jupyter` does it via the [Jupyter messaging protocol ](https://jupyter-client.readthedocs.io/en/stable/messaging.html). The only way of exchanging information with `comint-mode` REPLs is by sending code through the REPL prompt or parsing the output the REPL produces. Whereas in `emacs-jupyter`, information is exchanged using JSON messages and each message has a type that can have different kinds of content so it is easy to have different behaviors depending on the message type and the current context, e.g. if your are inside the REPL buffer or inside a source code buffer.

**Comment by prittjam** [comment]
It works! very nice and thanks. I'll try the default workflow and see how it goes.
