### ISSUE TITLE
Results output in org-mode

### ISSUE THREAD

**Issue by DonHugo69** [dzop/emacs-jupyter#31]
Thanks a lot for creating and maintaining this emacs package!

I am having some difficulties with the different output from `ob-jupyter` comparing to `ob-python`. Probably I misunderstand something but I would like to ask for some help.

I have the following document:

```org
#+TITLE: test
#+PROPERTY: header-args :session :exports both

#+BEGIN_SRC jupyter-python
def stringcomposition(k, string):
    composition = []
    for i in range(len(string) - k + 1):
        pattern = string[i : i + k]
        composition.append(pattern)
    return composition

# Test
k = 5
string = "CAATCCAAC"

result = stringcomposition(k, string)

# Sort results
result = sorted(result)
print(result)
#+END_SRC

#+BEGIN_SRC python 
def stringcomposition(k, string):
    composition = []
    for i in range(len(string) - k + 1):
        pattern = string[i : i + k]
        composition.append(pattern)
    return composition

# Test
k = 5
string = "CAATCCAAC"

result = stringcomposition(k, string)

# Sort results
result = sorted(result)
print(result)
#+END_SRC
```

I understand that the output of the result will depend on the header arguments of the source block and if use `print(result)` or just `result`.

`python :results output`
```org
#+RESULTS:
: ['AATCC', 'ATCCA', 'CAATC', 'CCAAC', 'TCCAA']
```
`jupyter-python`
```org
#+RESULTS:
: ['AATCC', 'ATCCA', 'CAATC', 'CCAAC', 'TCCAA']
: 
```
- The results are the same, even though jupyter seems to add a newline. Not a huge issue but is there a way to suppress it as it adds an unnecessary newline in the code block when exporting? 

`python :results output table`
```org
#+RESULTS:
| AATCC | ATCCA | CAATC | CCAAC | TCCAA |
```
`jupyter-python :results table`
```org
#+RESULTS:
| : ['AATCC', 'ATCCA', 'CAATC', 'CCAAC', 'TCCAA'] |
```
- `python` returns, as expected, a table containing the separate strings (this is my desired ouput here), but `jupyter` seems not to remove the leading colon which, I think, prevents the tabular output. 

Jupyter does print a table if I use `result` in the source block instead of `print(result)`
`jupyter-python`
```org
#+RESULTS:
| AATCC | ATCCA | CAATC | CCAAC | TCCAA |
```

If I want the output as a list:
`python :results output list`
```org
#+RESULTS:
: - AATCC
: - ATCCA
: - CAATC
: - CCAAC
: - TCCAA
```
`jupyter-python :results output list`
```org
#+RESULTS:
- : AATCC
- : ATCCA
- : CAATC
- : CCAAC
- : TCCAA
- :
```
- In `jupyter` the `:` and the `-` are swapped and thus the `:` will also appear in front of the strings in the exported document, plus the empty newline.

Is there a way to work around these glitches or am I just using it in a wrong way and/or have wrong expectations?

**Edit**
The following behavior was caused by still having the following snippet from [ob-ipython](https://github.com/gregsexton/ob-ipython) in iPython startup folder.

```py
import IPython
from tabulate import tabulate

class OrgFormatter(IPython.core.formatters.BaseFormatter):
    def __call__(self, obj):
        try:
            return tabulate(obj, headers='keys',
                            tablefmt='orgtbl', showindex='always')
        except:
            return None

ip = get_ipython()
ip.display_formatter.formatters['text/org'] = OrgFormatter()
```
Jupyter does print a table if I use `result` in the source block instead of `print(result)`
`jupyter-python`
```org
#+RESULTS:
:RESULTS:
|    | 0   | 1   | 2   | 3   | 4   |
|----+-----+-----+-----+-----+-----|
|  0 | A   | A   | T   | C   | C   |
|  1 | A   | T   | C   | C   | A   |
|  2 | C   | A   | A   | T   | C   |
|  3 | C   | C   | A   | A   | C   |
|  4 | T   | C   | C   | A   | A   |
:END:
```
- even though it is a table now, the strings have been separated into the single characters
A similar result is obtained if I select on element of the `result` list via `[result[0]]`
```org
#+RESULTS:
:RESULTS:
|    | 0   | 1   | 2   | 3   | 4   |
|----+-----+-----+-----+-----+-----|
|  0 | A   | A   | T   | C   | C   |
:END:
```

Using `[result]` instead of `result`
```org
#+RESULTS:
:RESULTS:
|    | 0     | 1     | 2     | 3     | 4     |
|----+-------+-------+-------+-------+-------|
|  0 | AATCC | ATCCA | CAATC | CCAAC | TCCAA |
:END:
```
- this looks good, even though a header row and a row column have been added. Is there a way to remove them or control what they display?

**Comment by dzop** [comment]
The `org-mode` integration definitely could be done better. If you read [this section](https://github.com/dzop/emacs-jupyter#standard-output-displayed-data-and-code-block-results) in the README you will see a partial reason why the behavior of Jupyter source blocks are different.

One major reason is that, in addition to `output` or `result`, there are also [display-data](https://jupyter-client.readthedocs.io/en/stable/messaging.html#display-data) messages that can be sent by a kernel. `display-data` messages allow for multiple kinds of results to be displayed for the same source block. Similar to `:results append` for normal source blocks. I once attempted to go through `org-mode` using `append` to handle such cases, but there were too many quirks in transforming the result returned by Jupyter into a form suitable for `org-mode` and decided to implement a different solution. This has the downside that most of the result parameters are not supported, as you have found out. 

Also, I'm starting to think all of your examples are going through `ob-ipython` since `emacs-jupyter` ignores `:results list` and doesn't produce results like

```| : ['AATCC', 'ATCCA', 'CAATC', 'CCAAC', 'TCCAA'] |```

I suggest you remove `ob-ipython` from your `org-babel-load-languages` and ensure that it isn't loaded see https://github.com/dzop/emacs-jupyter/issues/16#issuecomment-463837219.

Another reason is that the `stdout` messages we get from the kernel can be broken up across different messages, so, in your example above, when you do `print(result)` we may receive `['AATCC', 'ATCCA'` in one message and then `, 'CAATC', 'CCAAC', 'TCCAA']` in a second message and we would have to concatenate the two together to form the full result. Although this wouldn't happen for such a small length of output, it would happen when a lot of output is being produced. One way around this is to queue the output until we have received all of it and this is what is done when `:async no` is provided, but the output is inserted whenever it arrives in the `:async yes` case which means we have to do a lot of processing to take into account the fact that related output can appear in different messages.

Again, the above points are not to say that better integration with how `org-mode` inserts results cannot be done. Any ideas on how the current implementation can be improved are welcome.

Now on to some of the points you mentioned:

> Not a huge issue but is there a way to suppress it as it adds an unnecessary newline in the code block when exporting?

The Jupyter source block just uses the output as returned by the Python kernel, it looks like the normal `org-mode` blocks trim all whitespace from the end of the string. You can do `print(result, end='')` to get around this behavior. `print`, by default, always adds a newline.

> Jupyter does print a table if I use `result` in the source block instead of `print(result)`
`jupyter-python`

The proper way to do this would be to use `result` without `print(result)`. Also see the next note.

> jupyter-python :results output list

As mentioned above and in the README link, Jupyter source blocks currently don't support most of the result parameters that `org-mode` supports. Although I see how parameters like `:results list` would be useful and probably should be supported.

The *real difference* between Jupyter and `org-mode`, as it relates to this point, is that Jupyter provides all the information necessary to distinguish different kinds of results through its [messaging protocol](https://jupyter-client.readthedocs.io/en/stable/messaging.html) whereas, for normal `org-mode` blocks, the type of the result needs to be specified through the header arguments. In the current implementation of `emacs-jupyter`, I chose to go the route of taking advantage of the information provided by Jupyter which means that the `:results` parameter doesn't need to be specified, and is mostly ignored. This has the downside that some of the `org-mode` specific features like `:results list` don't work although I see how they could be useful.

**Comment by DonHugo69** [comment]
@dzop Thanks a lot for your reply and detailed explanations!

> Also, I'm starting to think all of your examples are going through `ob-ipython` since `emacs-jupyter` ignores `:results list` and doesn't produce results like
`| : ['AATCC', 'ATCCA', 'CAATC', 'CCAAC', 'TCCAA'] |`

I checked the value of `org-babel-load-languages` and it looks fine
```el
((python . t)
 (jupyter-python . t)
 (emacs-lisp . t))
```
I realized that when I produced this output the snippet from `ob-ipython` was still in place. However, `jupyter-python :results table` and `print(result)` still produces
```org
#+RESULTS:
| : ['AATCC', 'ATCCA', 'CAATC', 'CCAAC', 'TCCAA'] |
```
whereas `jupyter-python :results table` and `result` produces
```org
#+RESULTS:
|   | AATCC | ATCCA | CAATC | CCAAC | TCCAA |
```
But as this issue can be bypassed by just using the standard header arguments together with `result` I would consider it minor.

> The Jupyter source block just uses the output as returned by the Python kernel, it looks like the normal `org-mode` blocks trim all whitespace from the end of the string. You can do `print(result, end='')` to get around this behavior. `print`, by default, always adds a newline.

Thanks, this does the trick!

Regarding the list output I realized that actually `jupyter` is nearly correct as 
```org
#+RESULTS:
- : AATCC
- : ATCCA
- : CAATC
- : CCAAC
- : TCCAA
```
will be exported correctly as an actual list in the resulting document. There are three issues in [Scimax](https://github.com/jkitchin/scimax/issues?q=is%3Aissue+colon+is%3Aclosed) and I think [this](https://github.com/jkitchin/scimax/issues/222) is the closest one but I am not sure how helpful this is for you as it seems that `emacs-jupyter` is build up from the ground and does not use `ob-ipython` as its base.

**Comment by dzop** [comment]
Actually the `(jupyter-python . t)` should just be `(jupyter . t)` as stated in the [README](https://github.com/dzop/emacs-jupyter#integration-with-org-mode). So it doesn't look like `emacs-jupyter` is being used. It must be that `ob-ipython` is loaded in some other way?

After you make the above change and call `org-babel-do-load-languages`, you can test if you are using `emacs-jupyter` by evaluating
`(setq jupyter--debug t)` and then running the code block. You should see something like the following in the `*Messages*` buffer

```
SENT: (:shell d44fdcae-216e-4ddb-862e-260443711c7b)
MESSAGE: (:iopub :status (:execution_state busy))
MESSAGE: (:iopub :execute-input (:code ... :execution_count 3))
```

**Comment by DonHugo69** [comment]
> Actually the `(jupyter-python . t)` should just be `(jupyter . t)` as stated in the [README](https://github.com/dzop/emacs-jupyter#integration-with-org-mode). So it doesn't look like `emacs-jupyter` is being used. It must be that `ob-ipython` is loaded in some other way?

`ob-ipython` is not installed anymore, the false entry is because of Doom Emacs loading [mechanism](https://github.com/hlissner/doom-emacs/blob/33ef90343e156f1123d6616a00ff7458018ab8f8/modules/lang/org/%2Bbabel.el#L30). Even if I avoid and use 
```el
(org-babel-do-load-languages
 'org-babel-load-languages
 '((emacs-lisp . t)
   (julia . t)
   (python . t)
   (jupyter . t))
```
the results are the same.

**Comment by dzop** [comment]
I don't see how you could have gotten the `:results list` or the `:results table` output since `emacs-jupyter` would ignore these parameters.

Also did you do `(setq jupyter--debug t)` before evaluating the code block and get the stuff in the `*Messages*` buffer?

Another thing you can try is to evaluate `(org-babel-jupyter-aliases-from-kernelspecs)` before running the block.

**Comment by DonHugo69** [comment]
> Also did you do `(setq jupyter--debug t)` before evaluating the code block and get the stuff in the `*Messages*` buffer?

`:results list`
```
SENT: (:shell 288c40a3-56dd-4593-ac68-7a318d5851da)
MESSAGE: (:iopub :status (:execution_state busy))
MESSAGE: (:iopub :execute-input (:code def stringcomposition(k, string):
    composition = []
    for i in range(len(string) - k + 1):
        pattern = string[i : i + k]
        composition.append(pattern)
    return composition

# Test
k = 5
string = "CAATCCAAC"

result = stringcomposition(k, string)

# Sort results
result = sorted(result)
# result
for i in result:
    print(i) :execution_count 1))
RUN-HOOK: jupyter-iopub-message-hook
DROPPING-REQ: da5cc9d3-13d3-4f04-84e9-048bd79cd822
RUN-HOOK: jupyter-iopub-message-hook
MESSAGE: (:iopub :stream (:name stdout :text AATCC
ATCCA
CAATC
CCAAC
TCCAA
))
RUN-HOOK: jupyter-iopub-message-hook
MESSAGE: (:shell :execute-reply (:status ok :execution_count 1 :user_expressions nil :payload []))
MESSAGE: (:iopub :status (:execution_state idle))
RUN-HOOK: jupyter-shell-message-hook
Code block evaluation complete.
RUN-HOOK: jupyter-iopub-message-hook
Code block evaluation complete.
```
`:results table`
```
SENT: (:shell 86a7d854-a876-4ba6-8e3f-eb76cd905b89)
MESSAGE: (:iopub :status (:execution_state busy))
RUN-HOOK: jupyter-iopub-message-hook
DROPPING-REQ: 2b475c6a-3e7f-4705-abb3-c57542fabdef
MESSAGE: (:iopub :execute-input (:code def stringcomposition(k, string):
    composition = []
    for i in range(len(string) - k + 1):
        pattern = string[i : i + k]
        composition.append(pattern)
    return composition

# Test
k = 5
string = "CAATCCAAC"

result = stringcomposition(k, string)

# Sort results
result = sorted(result)
result
# for i in result:
#     print(i) :execution_count 1))
RUN-HOOK: jupyter-iopub-message-hook
MESSAGE: (:iopub :execute-result (:data (:text/plain [’AATCC’, ’ATCCA’, ’CAATC’, ’CCAAC’, ’TCCAA’]) :metadata nil :execution_count 1))
RUN-HOOK: jupyter-iopub-message-hook
MESSAGE: (:shell :execute-reply (:status ok :execution_count 1 :user_expressions nil :payload []))
MESSAGE: (:iopub :status (:execution_state idle))
RUN-HOOK: jupyter-shell-message-hook
Code block evaluation complete.
RUN-HOOK: jupyter-iopub-message-hook
Code block evaluation complete.
```

**Comment by dzop** [comment]
OK, I see the issue. You are using `:async no` right? Sorry, in my setup I'm using `:async yes` which was why I got confused. With `:async no` I am getting the results that you are observing.

Currently there is a difference with how output is inserted using the `:async no` vs the `:async yes` case. In the `:async no` case, we go through the the normal `org-mode` result insertion which means that the `:results list` and the `:results table` are handled in the way that `org-mode` handles them. In the `:async yes` case, the results are inserted in an `emacs-jupyter` specific way and those parameters are ignored.

For the `:async no` case you can think of the code block as producing formatted org strings, e.g. when using `:results raw`. So there is no need to specify `:results table` since you will already get a formatted table. For the `:results list` case, `org-mode` sees

```
: AATCC
: ATCCA
: CAATC
: CCAAC
: TCCAA
```

as the result (since by the time the normal `org-mode` result insertion mechanism sees the result, it is already a formatted org string) and converts that into a list.

Note `:results list` is still not really supported, but works in this case. It wouldn't work correctly if the output has more lines than `org-babel-min-lines-for-block-output` since `emacs-jupyter` obeys this variable.

**Comment by dzop** [comment]
> The results are the same, even though jupyter seems to add a newline. Not a huge issue but is there a way to suppress it as it adds an unnecessary newline in the code block when exporting?

I think this is actually related to changes in Org 9.2.1. Are you using this version? I have updated the code to take into account Org 9.2.1 so you shouldn't have to specify `print("foo", end='')` if you are.

**Comment by DonHugo69** [comment]
> I think this is actually related to changes in Org 9.2.1. Are you using this version? I have updated the code to take into account Org 9.2.1 so you shouldn't have to specify `print("foo", end='')` if you are.

Indeed, I use version 9.2.1 and after updating your package, the newline is gone. Thanks!

**Comment by dzop** [comment]
Closing this since I think #40 is more relevant and the code has been updated to work with Org >= 9.2 in 7d726736049bd49505d5bd5ab8668507f7c2500f so the whitespace issues mentioned have been fixed.

**Comment by Yevgnen** [comment]
It would nice to have possibility to make `print(df)` also convert to `org` table.

**Comment by dzop** [comment]
If you just return `df` (assuming `df` is a DataFrame) you should be able to get an `org` table by doing what is mentioned in https://github.com/dzop/emacs-jupyter/issues/88#issuecomment-481893622.

**Comment by Yevgnen** [comment]
Yes, without `print` is ok and I'm using it all the time. But when tangling, statements like 

```
#+begin_src jupyter-python
df
#+end_src
```

or 

```
#+begin_src jupyter-python
some_function_that_has_valuable_return_but_without_assignment(params)
#+end_src
```

are meaningless statements in the resulting source file, and thus no output is there. Thought one can just not tangle these blocks. But still, output is gone.

**Comment by dzop** [comment]
I see. I don't think this is going to happen since that would require us to look at the `stdout` stream to detect if there is an `org-mode` table and there would be many issues doing this.

The benefit of Jupyter is that the result of a code block is tagged with a mimetype and the entire result is received by Emacs atomically, i.e. in one `:execute-result` message. In contrast, `stdout` is just a sequence of characters and there is no guarantee that one `print(df)` call corresponds to one `:stream` message received by Emacs so we would have to detect which stream message is the start of an `org-mode` table, which one is the end of a table, and store all the intermediate `:stream` messages as being part of the table. There would be a lot of edge cases to consider and it doesn't seem worth the trouble, but if you can come up with a reasonable solution I would consider adding it.

You could probably do something on the `python` side by overloading the `print` function to, whenever inside an IPython session, emit a `:display-data` message whenever it detects a dataframe. Here is how to emit a `:display-data` message: 

```python
from IPython.display import publish_display_data
publish_display_data({'text/org': tabulate(df, tablefmt="orgtbl"))});
```

**Comment by Yevgnen** [comment]
Thanks for detail explanation. That sounds reasonable. I find that even jupyter notebook does not deal with these cases neither.

**Comment by Yevgnen** [comment]
@dzop

Is it possible to display a `DataFrame` in a web page like currently what is support for widget? If it is, do I only need to implement some other format function or formate class? I may add the custom option for personal usages.

When a `DataFrame` is large, it would be like to display it in the browser which has better scrolling support or even the ability to integrate with package like [qgrid](https://github.com/quantopian/qgrid). With small `DataFrame`s, `tabulate` has already done a good job.

By the way, currently I'm using settings like this

```py
# -*- coding: utf-8 -*-

import re

import IPython
import pandas as pd
import tabulate

_IP = get_ipython()


class OrgFormatter(IPython.core.formatters.BaseFormatter):
    format_type = IPython.core.formatters.Unicode('text/org')
    print_method = IPython.core.formatters.ObjectName('_repr_org_')


def pd_dataframe_to_org(df, max_columns=50):
    if len(df) > max_columns:
        df = pd.concat([df.iloc[:max_columns], df.iloc[-max_columns:]])

    table = tabulate.tabulate(df,
                              headers='keys',
                              tablefmt='orgtbl',
                              showindex='always')

    if len(df) < max_columns:
        return table

    half = max_columns // 2
    rows = table.split('\n')
    ignored = re.sub(r'[^ |]', '.', rows[0]).replace('.|.', '...')

    return '\n'.join(rows[:half] + [ignored] + rows[-half:])


def dict_to_org(d, max_items=50, max_width=25):
    items = list(d.items())[:max_items]

    max_width = min(max(len(str(k)) for k, v in items), max_width)
    pattern = '{{k!s:>{width}}}: {{v!r:>{width}}}'.format(width=max_width)

    items = [pattern.format(k=k, v=v) for k, v in items]
    if len(d) > max_items:
        items += [' ' * (len(items[-1]) - 3) + '...']

    return '\n'.join(items)


def seq_to_org(s, max_items=50):
    s = list(s)
    if len(s) > max_items:
        half = max_items // 2
        s = s[:half] + ['...'] + s[-half:]
    items = ['{v!s}'.format(v=v) for v in s]

    return '{type}([{items}])'.format(type=s.__class__.__name__,
                                      items=', '.join(items))


_IP.display_formatter.formatters['text/org'] = OrgFormatter()
_ORG_FMT = _IP.display_formatter.formatters['text/org']
_ORG_FMT.for_type_by_name('pandas.core.frame', 'DataFrame',
                          pd_dataframe_to_org)

_PLAIN_FMT = _IP.display_formatter.formatters['text/plain']
_PLAIN_FMT.for_type(dict, lambda x, p, c: p.text(dict_to_org(x)))
_PLAIN_FMT.for_type(set, lambda x, p, c: p.text(seq_to_org(x)))
_PLAIN_FMT.for_type(list, lambda x, p, c: p.text(seq_to_org(x)))
```

The `list`, `set`, `dict` is converted to single line `org` tables by default, which looks bit weird. I'm interested in adding support for other types.

<img width="721" alt="Screen Shot 2019-08-01 at 10 43 25 PM" src="https://user-images.githubusercontent.com/16749790/62302938-d1942680-b4ad-11e9-8759-5e18337dfcb4.png">
