### ISSUE TITLE
ipdb and code evaluation

### ISSUE THREAD

**Issue by prittjam** [dzop/emacs-jupyter#35]
If you evaluate a region of code in the REPL while ipdb is running, emacs locks up. It seems there is no timeout.

**Comment by dzop** [comment]
How do you mean? You mean whenever you press `C-c C-c`? There is no waiting for a result to come back when you press `C-c C-c`. If you mean when you try to send code by pressing `RET` in the REPL there are timeouts.

Can you do `M-x toggle-debug-on-quit` and press `C-g` a few times whenever Emacs locks up to try and get a backtrace.

**Comment by prittjam** [comment]
I am using ipdb, e.g., as invoked by pdb.set_trace(). Unfortunately, ipdb runs in the minibuffer making it almost impossible to use. If you try to run something in the kernel while ipdb is running, which is also using the kernel, emacs will freeze since the kernel will never execute the code. There is no timeout that is triggered in this case. 

In general this is a larger problem with the environment. What you've done is excellent. What would make it amazing would be the ability to run a segment of code and if ipdb is invoked, have the program state available in the kernel at the point where the problem occurred. Then you could dynamically edit and run code at the point of the problem. The only REPL I know that can do this is MATLAB, and it makes for amazing productivity. It almost justifies the price of the license.

**Comment by dzop** [comment]
Yes an actual debugging protocol is needed in Jupyter so that debugging is better integrated with frontends. I believe support for a debugging protocol is in the works (see https://github.com/jupyter/debugger), but there does not seem to be much activity.

> If you try to run something in the kernel while ipdb is running, which is also using the kernel, emacs will freeze

How are you trying to run something else in the kernel? When I run

```python
import pdb
def f():
    pdb.set_trace()
    print('foo')
```

in a REPL cell and then run

```python
f()
```

in another REPL cell. I get popped into the minibuffer with a prompt `(Pdb)`. I can then evaluate any expression in the current stack frame using `p <ex>` and the value of `<ex>` is printed as output of the REPL cell whose input is `f()`.

If on the other hand you are talking about running `f()` as defined above from a `py` file, there does seem to be an issue since the minibuffer prompt is not shown and you cannot send anything to the kernel since it is in the busy state. But I still don't get any freezes. Can you give a minimum working example (MWE) that causes Emacs to freeze.

**Comment by poppyschmo** [comment]
I'm running into what may be the same issue. @prittjam would have to confirm. In my case, this crops up intermittently in a REPL buffer after sending a new code cell.

GNU Emacs 26.2 (build 1, x86_64-redhat-linux-gu, GTK+ Version 3.24.8)

![emacs-small](https://user-images.githubusercontent.com/12665556/58522826-e46d4080-8176-11e9-874f-c83de9318376.gif)

In the shot above, I don't hit any keys after sending the input but do hit return a few times after the minibuffer prompt has already been replaced by the error message.

```elisp
(ert-deftest jupyter-repl-ret-debug ()
  :tags '(repl)
  (let (jupyter-test-with-new-client)  ;; allow postmortem in UI
    (jupyter-test-with-python-repl client
     (jupyter-ert-info ("Kernel busy when reading from minibuffer")
      (jupyter-repl-replace-cell-code "def foo(x):\n\treturn x\n")
      (jupyter-test-repl-ret-sync)
      (jupyter-repl-replace-cell-code "foo(True)")
      (jupyter-test-repl-ret-sync)
      (save-excursion
        (jupyter-repl-backward-cell)
        (should (equal "True" (string-trim (jupyter-repl-cell-output)))))
      (jupyter-repl-replace-cell-code "%debug foo(True)")
      (let ((err (should-error (jupyter-test-repl-ret-sync))))
        (should (equal err '(error "Kernel busy"))))))))
```
This test won't work in headless ert; it'll just block, waiting for standard in (as expected).
In interactive mode, it passes maybe 50% of the time on both X and terminal.

```console
emacs ${nw} -Q \
  -L ${jupyter} -L ${websocket} -L ${simple-httpd} -L ${zmq} \
  -l jupyter-test.el -l test-helper.el \
  --eval '(ert-run-tests-interactively (quote jupyter-repl-ret-debug))'
```

**Comment by dzop** [comment]
OK I think I found the issue here. I believe it has to do with the concurrency of timers in Emacs. Whenever we receive a message from the kernel we fire off a new timer to handle it on the next command loop this effectively allows the message handlers to queue up and be handled whenever Emacs says that it wants to handle them, e.g. when waiting for a reply message.

`jupyer-repl-ret` is sending an `:is-complete-request` and **waiting** for an `:is-complete-reply`. If it doesn't receive one within a timeout it will call itself again, but with `jupyter-repl-use-builtin-is-complete` set to `t`. The message handler for the `:is-complete-reply` message sends an `:execute-request` and the kernel then sends back an `:input-request` and the method `jupyter-handle-input-request` then calls `read-from-minibuffer`. All of this seems to be happening before `jupyter-repl-ret` returns from waiting. Since we are reading from the minibuffer,  the timeout is being hit before the `:is-complete-reply` message is received by `jupyter-repl-ret`. This means that it will call itself again, but because the kernel is still waiting for input, it is busy hence the `Kernel busy` error.

The gist of the problem can be shown by running the following function and waiting a few seconds

```emacs-lisp
(defun jupyter-issue-35 ()
  (cl-destructuring-bind (manager client)
      (jupyter-start-new-kernel "python")
    (unwind-protect
        (let ((reply-msg
               (jupyter-wait-until-received :is-complete-reply
                 (let ((req (jupyter-send-is-complete-request client
                              :code "%debug foo(True)")))
                   (prog1 req
                     (jupyter-add-callback req
                       :is-complete-reply
                       (lambda (_)
                         (read-from-minibuffer "ipdb> "))))))))
          (unless reply-msg
            (error "Kernel busy")))
      (jupyter-stop-channels client)
      (jupyter-shutdown-kernel manager))))
```

**Comment by dzop** [comment]
Looks like this can be fixed by using `with-timeout-suspend`, e.g.

```emacs-lisp
(let ((timeouts (with-timeout-suspend)))
  (unwind-protect
      (read-from-minibuffer "ipdb> ")
    (with-timeout-unsuspend timeouts)))
```

We can wrap the body of `jupyter-handle-input-request` using the above and the timeouts that `jupyter-wait-until-received` will be prevented from firing until input has been read.

**Comment by poppyschmo** [comment]
Thanks for the breakdown. Wrapping `read-from-minibuffer`, as described, indeed fixes the issue (for me).

**Comment by dzop** [comment]
I don't really use python that much so I'm not sure how the experience is with ipdb and the minibuffer, but one idea I thought of is to, whenever the kernel requests input, have a separate input buffer open to type in the input. Then, when you are done, you can press `C-c C-c` in the buffer to send the input to the kernel. So the whole process would be similar to how magit asks for a commit message.

This still wouldn't solve the problem of the kernel being busy when waiting for input from the user, but thats more of an issue with the Jupyter spec. The purpose of opening up a buffer would be so that we don't restrict the user to have to stay in the minibuffer while debugging.

Another option along the same lines would be to bind `recursive-edit` when the input minibuffer is active and set it up so that exiting recursive edit brings you back into the minibuffer to enter input. So you would be able to toggle between entering input and using Emacs normally to browse the code while debugging.

We could also combine the two. Provide two bindings, one to call `recursive-edit` just to browse the code before entering input and another to open up an input buffer to enter more content than what would be convenient to type in at the minibuffer prompt.

**Comment by poppyschmo** [comment]
I'm inclined to vote for door number 3 (the combo), that is
- Minibuffer + `recursive-edit` for normal debugger commands (personally prefer this over some kind of transient, hydra-like menu, for example)
- Optional separate buffer for easier multi-line input

Though I have no strong opinion either way and am curious what others might have to say.

> more content than what would be convenient to type in at the minibuffer prompt

... especially with regard to the "significant whitespace" in Python. In the terminal, there's little choice but to use the debugger's `interact` command for multi-line input, although we're rewarded with continuation prompts for doing so.

In Emacs, using `interact` is currently a piecemeal affair, meaning ipdb users would have to send each line of a multiliner separately if opting to use continuation prompts for alignment, which is obviously impractical.

A dedicated input buffer would render this moot for one-off multi-line cases (guessing they're the most common). It would also free users from having to think about retaining modifications to local variables, which is an issue when exiting a subordinate `interact` REPL and returning to the debugger.

If implementing such a buffer, it may be worth accommodating routine rejections that may occur (perhaps due to artificial scoping/namespacing quirks imposed by the debugger, which can be tough to anticipate). By this, I mean preserving the failed input payload by burying a buffer instead of killing it or maybe making its contents yankable during the requisite "fallback" `interact` session.

(BTW, sending a lone `C-q`/`quoted-insert` `"^D"` from the minibuffer seems to work for bailing out of an `interact` session.)

Hopefully, other ipdb users will weigh in.

**Comment by dzop** [comment]
> If implementing such a buffer, it may be worth accommodating routine rejections that may occur (perhaps due to artificial scoping/namespacing quirks imposed by the debugger, which can be tough to anticipate). By this, I mean preserving the failed input payload by burying a buffer instead of killing it or maybe making its contents yankable during the requisite "fallback" interact session.

We can have an `input-request` history variable that stores the history of input requests on a per client basis and provide key bindings that yank text from the history into the input buffer, replacing its previous contents. This is similar to how the magit `git-commit-mode` buffer works as well. You can replace the contents of the commit buffer with previous commit messages using `M-n` and `M-p`.

**Comment by poppyschmo** [comment]
Thanks for a5e584e. Ipdb input has been working great ever since.

So far, I haven't had much occasion to send anything sizable to the debugger. I do rely pretty regularly on the built-in minibuffer history commands for (re)evaluating little oneliners and such.

So I would think frequent users of a dedicated buffer might appreciate having the `input-request` history available. Although the likelihood of any such users finding their way to this issues thread to chime in may be rather slim, given the original topic.

**Comment by dzop** [comment]
Closing since I believe the original issue has been solved by a5e584e. I also opened up #184 to further discuss having a better `input-request` interface.

**Comment by littlehome-eugene** [comment]
Sorry to bring up old issue,

I have the same problem.. I have the latest emacs-jupyter package installed.


I'm using
```

import pdb
pdb.set_trace()
```

and it drops down to a mini buffer..

What am I missing?

**Comment by colormotor** [comment]
Regarding the ideas proposed above, would it not make sense to handle this like an IDE, such as Spyder? 
In this case the input to the REPL is forwarded to pdb instead of being sent directly to jupyter. This can lead to strange behaviors at times, but is definitely a much more comfortable debugging experience than having to deal with the minibuffer.

**Comment by colormotor** [comment]
@littlehome-eugene do you have the REPL buffer open and associated to the script buffer?
