### ISSUE TITLE
emacs 100% cpu freeze when editing text in repl buffer

### ISSUE THREAD

**Issue by vv111y** [dzop/emacs-jupyter#38]
It seems to happen after I paste text from another buffer, or it may be when I go between normal and insert state (using evil) under certain unknown circumstances. 
- it is not another child process, it is emacs itself
- doesn't trigger debugger, so I can't use that
- using spacemacs on either mac or linux   

info:
``` 
- OS: darwin (but happens on linux too)
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 4b195ddfc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
```
only killing emacs and restarting works.

**Comment by non-Jedi** [comment]
I've seen this. I can reproducer consistently without pasting by doing the following with the IJulia kernel.

```
]activate ~/repos/ChemicalEngineeringToolbox.jl
]st
```

**Comment by dzop** [comment]
Yeah I have had some issues with pasting in the REPL that I have been working on. I was getting freezes when I tried to undo a paste, but that should be fixed in 9484735c0651a412ad6e2a4d6628c740feda1419. I've always been able to `C-g` from the freeze though.

@non-Jedi  it might have to do with the package prompt `]` interfering with syntax parsing. Are you using an `emacs-jupyter` newer than 6eec94a97fe2e51f2f1a0e5157dceb6e0b05ef40? Also are saying that `]activate ~/repos/ChemicalEngineeringToolbox.jl` runs but then after you type `]st RET` everything freezes?

As a general tactic for attempting to un-freeze Emacs you can go to a shell and do

```
pkill -P <PID> -SIGUSR2
```

where `<PID>` is the process ID of the frozen Emacs. Try to do this a few times to see if you can get Emacs to spit out a backtrace. See [debug-on-event](https://www.gnu.org/software/emacs/manual/html_node/elisp/Error-Debugging.html#Error-Debugging).

**Comment by non-Jedi** [comment]
I'm using an older commit. Will upgrade and retest. And yes, the `activate` command runs successfully, and then emacs freezes as soon as you type `]`. Sending a `SIGUSR2` signal hasn't had any effect in the past.

**Comment by dzop** [comment]
@non-Jedi Yes can you make a new issue. In the new issue can you mention how the Julia REPL displays that prompt. Does it truncate it or just display the whole prompt? I'm not actually sure how to fix this because if we just display the whole prompt then basically half of your screen will be the margin. An alternative would be to insert the prompt directly in the buffer without using the margin, but I think this would take a lot of refactoring. The nice thing about using the margin is that the whole contents of the REPL buffer is either code or output without any prompt strings.

**Comment by vv111y** [comment]
What a relief I'm not the only one. It does it with evil-surround too. 
no interrupt seems to work here, I have to kill it everytime. 
I'll see if I can poke around and find something. I may be spending A LOT of time in here

**Comment by dzop** [comment]
@vv111y I can reproduce the issue with `evil-surround`. Its a good starting point for investigating the problem further. Regarding pasting into the REPL, since this may be a different problem, can you provide a recipe for reproducing the freeze?

**Comment by dzop** [comment]
OK I've found the issue with `evil-surround`. It has to do with the fact that the buffer is narrowed whenever changing the surround characters. The functions responsible for marking parts of the buffer as cell code (for font lock purposes) need to look at the parts of the buffer outside of the narrowed region. So since the buffer is narrowed, these functions are unable to mark the newly inserted surround characters as cell code which seems to be the cause of the freeze.

Also, the narrowing happens because we use the `field` text property to mark cell code from cell output. When changing the surround, `evil` narrows to the current field (the `evil-narrow-to-field` call in `evil-motion-range`).

**Comment by Salompas** [comment]
I am also having a problem with the REPL buffer freezing. I have never been able to recover with `C-g` or even `pkill` and always need to force quite Emacs. The issue seems to occur whenever editing text in the REPL buffer. I am using version `20190223.305`.

**Comment by dzop** [comment]
@Salompas When does the freeze happen? Does it happen when you try to indent a line? When you press enter to start a new line? Compared to the built-in `python-mode` from `python.el`, does `elpy` change any font locking stuff, e.g. what are the values of `font-lock-fontify-region-function` and `syntax-propertize-function` when inside an `elpy` buffer. Also, in the REPL buffer what is the value of `after-change-functions`?

**Comment by dzop** [comment]
@vv111y The latest master fixes the issue with `evil-surround`, but may also fix your other issue. Could you try it out and let us know.

**Comment by Salompas** [comment]
> @Salompas When does the freeze happen? 

The freeze happens when I am typing in the REPL. I usually work with an `org` file opened and split screen with the REPL buffer. After switching to the REPL buffer, if I start typing something and then try to delete some part of it, then that is usually when it freezes. I've been using `sympy` lately and it happens very consistently when typing Python code.

>Does it happen when you try to indent a line? 

It does not happen when I try to indent a line, simply because I am typing line by line on the REPL, so there is no indentation going on.

> When you press enter to start a new line? 

Also no. It happens while typing text and then deleting characters before pressing RET. Say you type something like `sympy.Matrix([1, 2])*sympy.Matrix([[3, 4]])` and then go back to the beginning of the line to change `Matrix` to something else, then it would freeze.

> Compared to the built-in `python-mode` from `python.el`, does `elpy` change any font locking stuff, e.g. what are the values of `font-lock-fontify-region-function` and `syntax-propertize-function` when inside an `elpy` buffer. Also, in the REPL buffer what is the value of `after-change-functions`?

Inspecting these variables from the REPL buffer, I get:
- `C-h v font-lock-fontify-region-function`:
<img width="642" alt="screen shot 2019-02-27 at 8 30 52 am" src="https://user-images.githubusercontent.com/7663115/53493717-00732000-3a6a-11e9-9d73-2161caeb1830.png">

- `C-h v syntax-propertize-function`
<img width="646" alt="screen shot 2019-02-27 at 8 30 31 am" src="https://user-images.githubusercontent.com/7663115/53493692-f3eec780-3a69-11e9-8680-64bbd570eec0.png">

- `C-h v after-change-functions`
<img width="637" alt="screen shot 2019-02-27 at 8 32 59 am" src="https://user-images.githubusercontent.com/7663115/53493818-4b8d3300-3a6a-11e9-8ffe-1828ecbfbe79.png">

**Comment by dzop** [comment]
@Salompas Can you actually show the font-lock-fontify-region-function and syntax-propertize-function whenever you are in a normal python buffer, e.g. opening a .py file. Also if you are able to get the freeze consistently, can you provide a minimum number of steps to reproduce it.

**Comment by Salompas** [comment]
> Also if you are able to get the freeze consistently, can you provide a minimum number of steps to reproduce it.

I've been able to get it to freeze consistently (tested 4 times and froze on all) by:
1. Launch Emacs and create a new org file;
2. Create a `jupyter-python` code block and type `print('hi')` and execute with `C-c C-c` to get the REPL buffer started;
3. `C-x 3` to split the screen, `C-x o` to the other buffer and `C-x b` to make the REPL buffer visible;
4. Type:
`from sympy import *` and hit RET
5. Then type:
`symbols('a')*Matrix([1,2])` and without hitting RET move the cursor to the end of the line with `C-e`, then `C-b` until the cursor is sitting on the parenthesis `(` of `symbols`, then hit `M-delete` to delete `symbols` and Emacs will freeze and CPU usage will go to 100%ish

**Comment by Salompas** [comment]
> @Salompas Can you actually show the font-lock-fontify-region-function and syntax-propertize-function whenever you are in a normal python buffer, e.g. opening a .py file.

-  `font-lock-fontify-region-function`:
<img width="637" alt="screen shot 2019-02-27 at 12 20 27 pm" src="https://user-images.githubusercontent.com/7663115/53509577-1264bb00-3a8a-11e9-89d1-28c0998cf519.png">

- `syntax-propertize-function`:
<img width="635" alt="screen shot 2019-02-27 at 12 21 10 pm" src="https://user-images.githubusercontent.com/7663115/53509640-2c060280-3a8a-11e9-867c-ed81a4271f1f.png">

**Comment by dzop** [comment]
@Salompas OK, I've been able to reproduce this freeze. It is related to `python.el` related font lock stuff and doesn't have anything to do with `elpy`. It looks like something in `python-info-docstring-p` which is called by `python-font-lock-syntactic-face-function`.

**Comment by dzop** [comment]
@Salompas Should be fixed on latest master.

**Comment by Salompas** [comment]
> @Salompas Should be fixed on latest master.

Seems to be working!!!! Thank you very much for fixing! I'll keep testing and post if I find other freezes.

**Comment by vv111y** [comment]
@dzop thanks, you are really on this. It's great to see you so active getting this in top shape.

I'll test it out

**Comment by vv111y** [comment]
so far so good. Will spend a little more time with it to be sure.

**Comment by dzop** [comment]
@vv111y Does the freeze continue to happen for you or can this issue be closed?

**Comment by vv111y** [comment]
Yes, thank you
