### ISSUE TITLE
Specifying file doesn't seem to work correctly?

### ISSUE THREAD

**Issue by SirSharpest** [dzop/emacs-jupyter#47]
Running the following produces a blank file. Have I misunderstood the functionality of file? If so what is the correct way to do this?

```
#+BEGIN_SRC jupyter-python :session py :file ./test.png
import matplotlib.pyplot as plt
plt.plot([1,2,3,4])
#+END_SRC
```

**Comment by non-Jedi** [comment]
Probably a dup of #16.

**Comment by dzop** [comment]
Is your Org version >= 9.2? The semantics of `:file` has changed in Org >= 9.2, you also need to specify `:results link` for it to work. Specifying `:file` by itself now means to write whatever the source block *returns* to file.

So it should be

```
#+BEGIN_SRC jupyter-python :session py :file ./test.png :results link
import matplotlib.pyplot as plt
plt.plot([1,2,3,4])
#+END_SRC
```

However if you specify `:async yes` everything should work without `:results link`. You may also need to add `%matplotlib inline` before the plot call, see https://ipython.readthedocs.io/en/stable/interactive/plotting.html#id1.

Also note, there is an issue about consistent use and meaning of header arguments #40.

**Comment by SirSharpest** [comment]
I'm using org 9.1.9 - Updating to use async works. Thanks!

Any idea why the async is required?

**Comment by dzop** [comment]
For `:async yes` we have a custom result insertion method that doesn't go through `org-mode` (the `:async no` case does) and therefore doesn't follow the semantics of `org-mode`s header arguments in the same way. The main reason this is done is so that when `:async yes` is specified, results are inserted in the buffer as they come in much like a Jupyter notebook. In the `:async no` case, the results are collected first and then inserted (through `org-mode`s result insertion) after the code block finishes.

I opened #40 to address the consistency of how header arguments are handled in the `:async yes` vs `:async no` case.

**Comment by dzop** [comment]
Closing this as #40 is more relevant.
