### ISSUE TITLE
PNG output rather than SVG in IHaskell

### ISSUE THREAD

**Issue by GregorySchwartz** [dzop/emacs-jupyter#48]
From https://github.com/dzop/emacs-jupyter/issues/16#issuecomment-465722035

For no `:option no-svg`:

```
MESSAGE: (:iopub :display-data (:data (:image/png iVBORw0 ...
```

For `:option svg`:

```
MESSAGE: (:iopub :display-data (:data (:text/html <img src="data:image/svg+xml;base64,PD94bWw
```

**Comment by dzop** [comment]
Can you checkout the [haskell-svg](https://github.com/dzop/emacs-jupyter/tree/haskell-svg) branch and see if that works for you. You will have to add `:display html` to your source blocks for right now since PNG takes precedence over html. So for blocks that display images they will have to look like

```
#+BEGIN_SRC jupyter-haskell :display html ...
```

Note, PNG takes precedence over html since I think IJulia or IPython will return html as well as image data like PNG, but we can't really do much with html in `org-mode`.

To get around having to specify `:display html` you can add the following to your init file

```emacs-lisp
(setf (alist-get :display org-babel-default-header-args:jupyter-haskell) "org html jpeg png markdown latex plain")
```

this effectively changes the order in which mimetypes are searched for a result, see `jupyter-org-mime-types` for the default order.

**Comment by GregorySchwartz** [comment]
I submitted a patch to IHaskell, so this may not be necessary. I need to test the merged code first.

**Comment by dzop** [comment]
That's great! Hopefully it works out. I did some investigation into why they used HTML instead of SVG when you first raised this issue a while ago and found https://github.com/gibiansky/IHaskell/issues/187 which seems to be where they first mentioned using HTML instead of SVG in the commit that closed the issue.

**Comment by GregorySchwartz** [comment]
Okay, https://github.com/gibiansky/IHaskell/pull/1010 should solve this issue.
