### ISSUE TITLE
Use jupyter prefix instead of jupy for org-mode src-blocks

### ISSUE THREAD

**Issue by non-Jedi** [dzop/emacs-jupyter#5]
I haven't yet tried out the org-mode integration because my current setup uses ob-ipython for that; it would be nice if I could use both ob-ipython and emacs-jupyter in the same org document, so I could make the transition slowly, but that isn't currently possible because ob-ipython also uses `jupyter-language` as language names in SRC blocks. Since it's a more established package, it probably makes sense to change that here if it's going to change. Possible alternatives:

- `language-jupyter`
- `jupy-language`
- `ejupyter-language`
- `jupyter.language`
- `jupyter_language`
- ...

**Comment by dzop** [comment]
I would rather stick with the `jupyter` prefix seeing as `ob-ipython` has not had a commit in 9 months. But you are right that there is a barrier to entry due to the name clashing with `ob-ipython`. `jupy-language` sounds pretty good. I will update the `org-mode` support to use `jupy`. The issue of sticking with `jupyter` or `jupy` can be considered again in the future.

**Comment by stardiviner** [comment]
Hi, I saw this issue, I agree with @dzop , use `jupy-` prefix is kind of weird. Not helpful for reading and identify source blocks. I think `jupyter` prefix is necessary. How about `jupyter/language`, just and proposel, I don't know whether Org Mode Babel parameters parsing support this. I also like `jupyter_language` too.

**Comment by dzop** [comment]
I don't think `ob-ipython` is going to be accepting a pull request any time soon, so I think its better that all the changes happen in `emacs-jupyter`. I would rather have the separator be `-` rather than `/` or `_` since `-` is more of a canonical word separator in Emacs.

Seeing as this project is starting to pick up steam and `ob-ipython` looks to be abandoned, maybe it is time to just switch over to a `jupyter` prefix.

**Comment by non-Jedi** [comment]
I probably agree at this point; now that I've got emacs-jupyter setup, I've uninstalled ob-ipython completely and see no need for it any longer. It is funny; I think this is the first time I've seen a GH issue where it was reused for the opposite of the original issue. It works here though. :)

**Comment by dzop** [comment]
Well it is still under the general issue of (in)compatibility with ob-ipython :wink: 🏴.

**Comment by stardiviner** [comment]
Great, I like consistent!
