### ISSUE TITLE
Colour in Results block? 

### ISSUE THREAD

**Issue by MasonProtter** [dzop/emacs-jupyter#55]
Currently, the code shown in the output block is black and white whereas an associated repl session has the proper colours. Is there a way around this? 

Here's an example:

![Screen Shot 2019-03-11 at 11 18 36 AM](https://user-images.githubusercontent.com/29157027/54143588-c1d95000-43ef-11e9-8415-19157dec89df.png)

**Comment by dzop** [comment]
I did previously try to get color in code block output. The functions used to colorize the ANSI escape sequences in the REPL are the same ones used in the `org-mode` output block, the difference is that `org-mode` strips the color for some reason that I haven't put in the time to figure out yet. Most likely it is related to using text properties to add in the color and how `org-mode` does its fontification using `font-lock`.

Thinking about it again, I don't think it is correct to remove the ANSI escape sequences in `org-mode` output since we lose information that the kernel sent. We should be able to add color by inserting the ANSI escape sequences into the buffer, instead of stripping them and adding the colors as text properties before insertion (which is what the REPL does), and use `ansi-color-apply-on-region` to overlay them with color. This way we use overlays instead of text properties so we don't interfere with `font-lock`. The only downside is that overlays are known to slow down editing when there are a lot of them in the buffer.

**Comment by dzop** [comment]
Also as a side note, it looks like you use `rainbow-delimiters-mode`. You can also enable that in the REPL by adding `rainbow-delimiters-mode-enable` to `jupyter-repl-mode-hook`.
