### ISSUE TITLE
Can emacs-jupyter support Clojure's Clojupyter kernel?

### ISSUE THREAD

**Issue by stardiviner** [dzop/emacs-jupyter#60]
I hope emacs-jupyter can support Clojure's Clojupyter kernel https://github.com/clojupyter/clojupyter

**Comment by dzop** [comment]
I don't see why not. Jupyter is a messaging protocol that is language agnostic so if Clojupyter implements the Jupyter messaging protocol then should mostly work with `emasc-jupyter`. Of course there are always going to be some quirks specific to the language that requires some more manual intervention, like supporting the `:dir` header argument in `org-mode`.

Being as I don't use `clojure` at all, I won't be looking at how to integrate it with `emacs-jupyter`. But I will help anyone who would like to submit a pull request to add in support.

All of the code specific to `clojure` should go into its own file, `jupyter-clojure.el`. This file will get loaded the first time a client connects to a Clojupyter kernel. In this file you can override methods that `emacs-jupyter` uses to add in support for `clojure` languages. Many of the methods that can be overridden are listed [here](https://github.com/dzop/emacs-jupyter#modify-behavior-depending-on-kernel-language), but this may not be an exhaustive list as I have not updated it in a while. Look at the `jupyter-python.el` and `jupyter-julia.el` files for examples (start with `jupyter-python.el` since its less code).

If there is a specific scenario where `emacs-jupyter` doesn't do what is expected when using Clojupyter, there is probably a method that can be overridden to make `emacs-jupyter` do the right thing. If not, we can always add a new one for that scenario.

Also note, you can show the flow of messages sent to/from the kernel in the `*Messages*` buffer by setting `jupyter--debug` to `t`.

**Comment by dzop** [comment]
OK, I looked into this somewhat just because I was curious and opened up some issues over at Clojupyter that someone more familiar with Clojure can take a stab at (https://github.com/clojupyter/clojupyter/issues/85 and https://github.com/clojupyter/clojupyter/issues/84).

**Comment by dzop** [comment]
Also to see the `stdout` of Clojupyter to look at the logging it produces you can open up the REPL buffer and call `jupyter-repl-display-kernel-buffer`.

**Comment by stardiviner** [comment]
I will take a look to try whether I can do this. Thanks for your tips @dzop .

**Comment by dzop** [comment]
OK, the Clojupyter devel branch appears to be working fine with `emacs-jupyter` 569ae50214cbf5beb77d1efd8a07e95b248bce13. For some reason Clojupyter did not like it when an empty code string was sent to synchronize the client and kernel state before sending the real code for evaluation. It wasn't necessary anyways.

Let me know if you find any issues.

**Comment by stardiviner** [comment]
@dzop Thanks for quickly check this out. I have installed the latest version of `emacs-jupyter` and `clojupyter`'s `devel` branch. Then compiled `devel` branch, and override the original `clojupyter` binary file in `~/.local/share/jupyter/kernels/clojure/`. But still got same error message:

```
executing Jupyter-Clojure code block...
Kernel did not read connection file within timeout
```

**Comment by stardiviner** [comment]
After enabled `jupyter--debug`: got useless info:
```
executing Jupyter-Clojure code block...
START: nil
START-CHANNEL: (:shell)
START-CHANNEL: (:iopub)
START-CHANNEL: (:stdin)
Kernel did not read connection file within timeout
STOP-CHANNEL: (:shell)
STOP-CHANNEL: (:iopub)
STOP-CHANNEL: (:stdin)
QUIT: nil
```

**Comment by dzop** [comment]
It does take a long time to startup the Clojupyter kernel, but have never ran into this. Maybe increase `jupyter-long-timeout` to 20?

**Comment by stardiviner** [comment]
I also tried to use another way "accessing Jupyter notebook in Docker container directly" as in issue #61 

Here is my steps:
```org
#+begin_src sh
docker run --name clojupyter --rm -p 8888:8888 kxxoling/jupyter-clojure-docker
#+end_src

In Org Mode:

#+begin_src sh :dir /docker:clojupyter:/home/clojure/.local/share/jupyter/runtime/
ls kernel-*.json
#+end_src

#+RESULTS[<2019-03-26 10:05:59> 1f7ffba7cf2d6bf59de44e36acc5ed8ed3d7822b]:
: kernel-31d60bee-4fa2-43b2-ae45-d0abd9732274.json

#+BEGIN_SRC jupyter-clojure :session /docker:clojupyter:/home/clojure/.local/share/jupyter/runtime/kernel-6e17cf21-aec8-481a-a3fb-58165e1d6eea.json
(+ 1 1)
#+END_SRC
```

**Comment by stardiviner** [comment]
You're right, after setting the timeout longer, it is solved. Thanks soooo much!!!

**Comment by stardiviner** [comment]
Oh, I guess this is feedback for the Clojupyter `develop` branch patch commits. It works. I guess it will be merged to `master` someday. At the end, thanks for your work. :+1: :+1: :+1:

**Comment by dzop** [comment]
Note, `kxxoling/jupyter-clojure-docker` only exposes the 8888 port as seen below (the value of `$PORT` is at the top of the file)

https://github.com/kxxoling/jupyter-clojure-docker/blob/e979ce4a12ede32dafd5353e1c32f6fba827d488/Dockerfile#L45

You will have to expose **all** the ports in the `kernel.json` file so that they are accessible outside the docker container as mentioned in https://github.com/dzop/emacs-jupyter/issues/61#issuecomment-474210150.

**Comment by stardiviner** [comment]
I see. thanks, I copied that example down to my Org Mode notes.
