### ISSUE TITLE
Problem with sagemath jupyter kernel

### ISSUE THREAD

**Issue by benneti** [dzop/emacs-jupyter#62]
When having a jupyter kernel that ob-jupyter cannot handle (`sagemath` for example) installed one gets the following error when loading
when executing `(org-babel-jupyter-aliases-from-kernelspecs)` the error
 `replace-regexp-in-string: Wrong type argument: arrayp, nil ` occurs. The backtrace is:

```
Debugger entered--Lisp error: (wrong-type-argument arrayp nil)
  substring(nil 0 0)
  replace-regexp-in-string("[0-9]*" "" nil)
  org-babel-jupyter-aliases-from-kernelspecs()
  byte-code("\300 \210\301\302\303\"\210\304\305!\207" [org-babel-jupyter-aliases-from-kernelspecs add-hook org-export-before-processing-hook org-babel-jupyter-setup-export provide ob-jupyter] 3)
  #<subr require>(ob-jupyter)
  apply(#<subr require> ob-jupyter)
  require(ob-jupyter)
  org-babel-do-load-languages(org-babel-load-languages ((shell . t) (js . t) (C . t) (python . t) (emacs-lisp . t) (org . t) (latex . t) (jupyter . t) (jupyter . t)))
  (progn (org-babel-do-load-languages 'org-babel-load-languages org-babel-load-languages))
  eval((progn (org-babel-do-load-languages 'org-babel-load-languages org-babel-load-languages)) nil)
  org-babel-execute:emacs-lisp("(org-babel-do-load-languages 'org-babel-load-langu..." ((:colname-names) (:rowname-names) (:result-params "replace") (:result-type . value) (:results . "replace") (:exports . "code") (:session . "none") (:cache . "no") (:noweb . "no") (:hlines . "no") (:tangle . "no") (:lexical . "no")))
  org-babel-execute-src-block(nil ("emacs-lisp" "(org-babel-do-load-languages 'org-babel-load-langu..." ((:colname-names) (:rowname-names) (:result-params "replace") (:result-type . value) (:results . "replace") (:exports . "code") (:lexical . "no") (:tangle . "no") (:hlines . "no") (:noweb . "no") (:cache . "no") (:session . "none")) "" nil 369 "(ref:%s)"))
  org-ctrl-c-ctrl-c(nil)
  funcall-interactively(org-ctrl-c-ctrl-c nil)
  call-interactively(org-ctrl-c-ctrl-c nil nil)
  command-execute(org-ctrl-c-ctrl-c)
```

Assuming that the regex does something for the kernelspecs maybe this is useful:
```
> jupyter kernelspec list
Available kernels:
  julia-1.1    /Users/benneti/Library/Jupyter/kernels/julia-1.1
  sagemath     /Users/benneti/Library/Jupyter/kernels/sagemath
  python3      /opt/local/Library/Frameworks/Python.framework/Versions/3.7/share/jupyter/kernels/python3
```

EDIT:
I found the problem, namely that at somepoint `sagemath` becomes a `nil` in the `spec` language field which in turn lets the regexp in `(org-babel-jupyter-aliases-from-kernelspecs)`  fail.
The easy fix was removing the sagemath kernel, but I think there should be some default setup for kernels or a check that does not add a language to the list when it is not implemented.

If I can help in any way let me know.

**Comment by dzop** [comment]
Yes it looks like this is probably because sagemath doesn't set the language field in the kernel.json file. Can you show the kernel.json file in the sagemath directory shown by `jupyter kernelspec list`.

I believe sagemath is built ontop of python right? You can edit the kernel.json to put python as the `language` field if you plan on actually using the kernel.

I'm not so sure we should care too much about this case since every kernel should have a corresponding language right?

**Comment by benneti** [comment]
The kernel.json file looks like this
`{"display_name": "SageMath 8.6", "argv": ["/usr/bin/sage", "--python", "-m", "sage.repl.ipython_kernel", "-f", "{connection_file}"]}` .
Yeah it is built on top of python but it deviates in some regards even in the syntax.
I only had it installed to try it out so uninstalling was no problem for me and I don't know too much about it.

I am not sure wether it is a problem with emacs-jupyter or with the sagemath kernel, do you know what the language is used for by jupyter?
Maybe it could work to fallback to the kernel name as the language name?

**Comment by dzop** [comment]
The kernel name itself does not need to have anything to do with the language of the kernel since the name of the kernel is just the name of the directory in which the `kernel.json` file lives, so I think it would be too arbitrary to use it as the fallback for the language.

The `language` key is used to recognize the language of the kernel according to the Jupyter [spec](https://jupyter-client.readthedocs.io/en/stable/kernels.html#kernel-specs). Mainly to figure out which kernel language to use for a Jupyter notebook since the names of kernelspecs can differ for different users.

**Comment by benneti** [comment]
OK it sounds like the issue is with the sagemath kernelspec then.
