### ISSUE TITLE
jupyter-org-execute-to-point should stay within one kernel

### ISSUE THREAD

**Issue by dangirsh** [dzop/emacs-jupyter#63]
I often maintain multiple Jupyter kernels within one Org file via subtree properties. If I run `jupyter-org-execute-to-point`, it naively starts at the top of the file and executes all blocks. Ideally it would only execute blocks associated with the same kernel as the block at point. Unsure how hard this is to implement... 

Overall, the enhancements ported from Scimax are an excellent addition!

**Comment by dzop** [comment]
Yes it does seem to make more sense to execute all blocks associated with a single session. I think the issue here is that `point` doesn't have to be on a source block to "execute to point" so it isn't entirely clear how to select which kernel session to use. A solution to this would be to modify `jupyter-org-execute-to-point` to accept a `C-u` prefix that allows the user to select a session.

Also, great work by @UndeadKernel on porting those Scimax helper functions 👏 .

**Comment by UndeadKernel** [comment]
It's a good idea to at least restrict execution to jupyter-based source blocks. It's rather easy to check if a block is using a jupyter kernel. However, figuring out which session to use is tricky.

As @dzop mentioned, if point is outside a source block, which session should we account for? The closest source block to the north of point? We could of course restrict the function to work only if point is inside a source block (and then we just use that block's session).

I do like the option of being able to execute all source blocks up to a point: I often use bash source blocks to execute some data processing utilities that I then parse within a jupyter source block.

We could modify `jupyter-org-execute-to-point` so that it executes only jupyter related source blocks by default. With `C-u` it evaluates every source block. We then create a second function that evaluates only source blocks within a subtree? Something like `jupyter-org-execute-subtree`.

**Comment by dzop** [comment]
> The closest source block to the north of point?

Using the session of the closest Jupyter source block sounds interesting. I think we can have a customizable variable to be able to control this behavior, something like `jupyter-org-execute-behavior`. Then we can leave it up to the user to decide how to select a session. The ways of selecting a session I can think of right now are:

1. If multiple sessions can be used, have the user select one of them
2. Use the session of the closest source block
3. If point is on a source block that has a session, use that session

> I often use bash source blocks to execute some data processing utilities that I then parse within a jupyter source block.

I definitely think this should be allowed. Determining the session should only apply to Jupyter source blocks, any other kinds of source blocks should be allowed to run.

> We could modify `jupyter-org-execute-to-point` so that it executes only jupyter related source blocks by default. With `C-u` it evaluates every source block.

Right, I think we need to have a distinction between Jupyter source blocks which we want to only evaluate Jupyter source blocks corresponding to a session that we select in some way. So before evaluating any blocks, we select a session, then iterate over the blocks in the buffer and run them if

1. they don't have a session or, if they do, they aren't Jupyter source blocks
2. they are Jupyter source blocks with the same session that was selected

I do like the idea of widening which source blocks get evaluated so we can control whether or not (1) is done based on a `C-u` prefix.

> We then create a second function that evaluates only source blocks within a subtree? Something like `jupyter-org-execute-subtree`.

There already is `org-babel-execute-subtree`, but it does make sense to roll our own function so that it calls `jupyter-org-execute-to-point` so that executing a subtree will be aware of Jupyter source blocks.
