### ISSUE TITLE
Fail to cleanup kernel manager: file-exists-p passed nil

### ISSUE THREAD

**Issue by dangirsh** [dzop/emacs-jupyter#65]
Occasionally I hit `Wrong type argument: stringp, nil` when shutting down Emacs.

I traced it to `jupyter-kernel-manager--cleanup` passing `nil` to `file-exists-p`.

Unsure what the upstream cause is, but here's my quick-fix to guard against this:

Line 77 of `jupyter-kernel-manager.el`:

```
(when (and conn-file (file-exists-p conn-file))
      (delete-file conn-file))
```

**Comment by dzop** [comment]
Looking through the code, the `conn-file` slot of a kernel manager is never set to `nil`, but its initial value is `nil` and gets set to a connection file path only when `jupyter-start-kernel` has been called. So it looks like a kernel manager was created, but a kernel was never started? Does this happen when you previously started a REPL and received the error

`Channel not started in ioloop subprocess (...)`

where `...` is one of the channels like `:iopub`, `:shell`, etc., and then shutdown Emacs a short time afterwards? This is a scenario where it may be possible that a kernel manager was created, but no kernel was actually started (due to the error). If this is the case, it looks like your fix would be fine to add.

Also investigating this led me to find another bug with a kernel manager. Specifically, when a kernel is restarted using a kernel manager, the old connection file of the previously shutdown kernel is never actually removed, so thanks for that.

**Comment by dangirsh** [comment]
I can't confirm the specific `Channel not started in ioloop subprocess` error, but can say it's possible. I occasionally see kernels fail to start, and retrying usually helps. I also restart Emacs often. Will keep an eye out for that message.

**Comment by dzop** [comment]
I rarely see the error message, but I have seen it a couple of times in the past. I don't remember seeing it recently though and haven't found a way to reliably reproduce it. The error comes up if Emacs does not receive a confirmation from the channel subprocess (or ioloop) after telling it to start a channel socket. So it probably has something to do with reliability of subprocess communication in Emacs.

If you are seeing failures to start for the Julia kernel, it may have to do with pre-compilation of IJulia or some package you may be loading in your `.juliarc.jl` file.
