### ISSUE TITLE
jupyter-org-insert-src-block is unaware of the current kernel

### ISSUE THREAD

**Issue by dangirsh** [dzop/emacs-jupyter#66]
This issue can be added to the "kernel-awareness" category along with #63.

I'm guessing users mainly stick with one type of kernel, associated with their primary development language (Julia in my case). As such, it would be nice if `jupyter-org-insert-src-block` (which I run very often) didn't invoke a kernel selector every time.

The simplest option is likely to add a new configuration variable specifying a default kernel. The kernel selector behavior could still be accessible via a prefix-arg, or invoked when no default kernel is specified. If this was implemented, I'd set this configuration variable in my `.dir-locals.el` per-project and cover most of my use-cases.

Much better would be to infer the kernel from the context, when possible. This might be possible as part of handling #63.

If we decide on the simpler approach, I'd be happy to make a PR.

**Comment by dcherian** [comment]
If there's only one kernel, always use that one?

**Comment by dzop** [comment]
#63 is a little different, in that case we want to select the right `:session`. In this case we want to select the right kernel language. The two cases are similar in that we want to search nearby source blocks for information, so there is probably some general source block querying interface we can come up with to handle both cases.

To solve this particular problem we can just use the language of the closest Jupyter source block near `point` by adding the following logic to `jupyter-org-insert-src-block`:

1. Get the languages of the `org-babel-next-src-block` and the `org-babel-previous-src-block`
2. Use whichever language that corresponds to a Jupyter language
3. If both languages correspond to different Jupyter languages, ask for a kernel language to use
4. If no language corresponds to a Jupyter language, widen the search until there are no more source blocks. If there still are no blocks that correspond to Jupyter languages, ask for a kernel language to use.

Then a `C-u` prefix can be used to always ask for a kernel language instead of using the above logic.
