### ISSUE TITLE
melpa release not updating

### ISSUE THREAD

**Issue by dcherian** [dzop/emacs-jupyter#77]
The current version on melpa is from March 10. Is this intended?

**Comment by dzop** [comment]
There is something wrong with the MELPA package. I've opened up an issue over at MELPA, https://github.com/melpa/melpa/issues/6081. It's been around 2 weeks since I opened it, but the issue hasn't been addressed yet. You can use quelpa as mentioned [here](https://github.com/dzop/emacs-jupyter/issues/61#issuecomment-476764761) if you want the latest version until the issue is resolved.

**Comment by dzop** [comment]
The MELPA package is now being updated.
