### ISSUE TITLE
[Aesthetics] Whitespace cleanup after jupyter-repl-insert-banner?

### ISSUE THREAD

**Issue by dangom** [dzop/emacs-jupyter#79]
This is pretty much a non issue, but I have `show-trailing-whitespace` set to true, and because the conda Python banner has a trailing whitespace, the jupyter REPL buffer at my end has a trailing whitespace marked, which looks ugly.

I currently solve this issue with the following advice:

```el
  (defun jupyter-banner-cleanup-whitespace (orig-func &rest args)
    "The function jupyter-repl-insert-banner is responsible for inserting
a language banner into the beginning of the REPL buffer. The banner is the
first thing printed when we start a language interpreter.
The issue is that the Python banner contains trailing whitespaces, and so
may look ugly if the variable `show-trailing-whitespace' is set to t."
    (apply orig-func args)
    (whitespace-cleanup))

  (advice-add 'jupyter-repl-insert-banner :around #'jupyter-banner-cleanup-whitespace)
```

Would this merit a patch directly at emacs-jupyter?

**Comment by dzop** [comment]
I'm thinking maybe it would be better to just set `show-trailing-whitespace` to `nil` in `jupyter-repl-mode`? I could also see it being a problem with the REPL output having trailing whitespace, e.g. https://github.com/dzop/emacs-jupyter/issues/52#issue-417457656. Or is having the trailing whitespace in the REPL input too useful? I don't use `show-trailing-whitespace` so I don't really have an opinion on it.

We should also set `show-trailing-whitespace` to `nil` in the buffers returned by `jupyter-get-buffer-create` since those buffers are used to show the output of evalution results.

**Comment by dangom** [comment]
Indeed, for a REPL the likelihood of trailing whitespaces causing issues is close to none.

Your suggestion of locally setting show-trailing-whitespace to nil for REPL buffers does sound like a better solution.

**Comment by dzop** [comment]
Would you like to submit a pull request with the change? If so, could you also set `show-trailing-whitespace` to `nil` in the buffer returned by `jupyter-get-buffer-create`.

**Comment by dangom** [comment]
Hi @dzop, yes, I'll tackle it this weekend.
