### ISSUE TITLE
Jupyter-run-repl DWIM?

### ISSUE THREAD

**Issue by dangom** [dzop/emacs-jupyter#80]
I wanted to mimic some of spacemacs (and elpy, I suppose) functionality in that a single command will either start a REPL or switch to an existing one, if the buffer is already associated with a running kernel.
My naïve approach to this was:

```el
(defun jupyter-run-repl-or-pop-to-buffer-dwim ()
    "If a buffer is already associated with a jupyter buffer,
then pop to it. Otherwise start a jupyter kernel."
    (interactive)
    (if (bound-and-true-p jupyter-current-client)
        (jupyter-repl-pop-to-buffer)
      (call-interactively #'jupyter-run-repl)))
```
However, if I kill the kernel, it seems like the python buffer still lingers with `jupyter-current-client` set.
I was wondering whether this is the intended behaviour and I should adapt my solution or whether emacs-jupyter should handle dissociating clients from buffers if the kernel is killed?

**Comment by dzop** [comment]
How are you killing the kernel? By killing the kernel process itself?

Whenever you kill the REPL buffer, all the python buffers with `jupyter-current-client` set to the REPL client should be removed, see `jupyter-repl-kill-buffer-query-function` (the call to `jupyter-repl-interaction-mode` will unset `jupyter-current-client` in the python buffer).

Its not necessarily correct to destroy the clients after a kernel dies since the kernel can restart using the same connection information. So the problem is not so straightforward.

**Comment by dangom** [comment]
Yes, I was killing the kernel process directly. I noticed that if I shutdown the kernel, then it does all the cleanup as expected.
Sorry for opening this without further investigation.
