### ISSUE TITLE
Kernel busy: Queue command?

### ISSUE THREAD

**Issue by dangom** [dzop/emacs-jupyter#82]
Say I open a new REPL and type the following:

```py
In [1] import time
In [*] time.sleep(10)
In [3] 2 + 2
```
Then while the kernel is busy, pressing RET to evaluate a new line (here `2 + 2`) will not queue the request, but simply warn the user that the kernel is busy.
Would there be a simple solution for allowing commands to queue?

**Comment by dzop** [comment]
Yes you can send the command to queue, but I decided against it because the kernel doesn't respond to any requests when it is busy.

Normally when the kernel isn't busy, an `:is-complete-request` is made using the code of the current input cell when `RET` is pressed. The kernel will respond saying that the code is `complete` or `incomplete`. If `complete`, an `:execute-request` using the code of the input cell is made, otherwise a newline is inserted.

If we allow sending an input cell when the kernel is busy, we can't rely on the `:is-complete-request` since the kernel won't respond to that. This means we would introduce the possibility of having incomplete code sent to the kernel when it is busy. I decided against this since it defeats the purpose of there being an `:is-complete-request` in the first place.

I'm open to any suggestions though. Maybe the solution is to just not show another input prompt until the current input cell has finished executing? This is how `jupyter console` seems to work.

**Comment by dangom** [comment]
Right, I expected a queuing mechanism per analogy with async org mode source blocks.
But I guess the correspondence here is org <-> notebook and REPL <-> console.

> Maybe the solution is to just not show another input prompt until the current input cell has finished executing? This is how jupyter console seems to work.

On the one hand we have a visual feedback that computations are running by means of the `In [*]` so showing another input prompt can be confusing if users expect a queuing mechanism. On the other hand, the fact that the next prompt is there means that commands can already be typed in. For low latency computations ( time to completion <= time to type next command) having the next prompt in there is indeed a plus.

Once one knows that there is no queuing, there are no reasons to remove the prompt.

From my side, please feel free to close this issue.

**Comment by dcherian** [comment]
> Maybe the solution is to just not show another input prompt until the current input cell has finished executing? This is how jupyter console seems to work.

+1. I think consistency with jupyter console is a good idea.

**Comment by non-Jedi** [comment]
Personally, I like having the prompt there available to type in and get my next steps ready even if kernel is still busy. This is a jupyter REPL built on an editor, so it's expected to me at least that it will have features that make sense in an editor but wouldn't necessarily make sense in a console. Just my 2 cents, but I won't be super heart-broken either way.

**Comment by dzop** [comment]
Another possibility is to have `RET` behave the way it would with `jupyter-repl-use-builtin-is-complete` set to `t` when the kernel is busy, i.e. no `:is-complete-request` is used and the code is sent to the kernel if the user presses `RET RET`.

I agree that we should keep the current behavior of having a prompt appear even though the kernel is busy. I don't think we should introduce an artificial restriction to make the REPL appear more like the `jupyter console`. The REPL is just another Emacs buffer after all so it is easy to insert text wherever and there is no need to have to wait for output from the kernel before allowing more user input.

**Comment by dzop** [comment]
OK I added a new custom variable, `jupyter-repl-allow-RET-when-busy` which allows you to queue an input cell when the kernel is busy by pressing `RET` on an empty line, i.e. by pressing `RET RET`.
